### ISSUE TITLE
MabiIccoの同時発音(polyphony)

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#100]
今日はスペックについて質問があります。

1. MabiIccoの同時発音(polyphony)はいくつですか？

2. 同時発音本数を超える状況が来た場合、どのようなアルゴリズムで解決しますか？

3. 上記のスペック、アルゴリズムの駆動方式がマビノギクライアントと似ているか、同じですか？

4. (番外) 同時発音数値の現況をリアルタイムでモニタリングできる機能の導入は可能でしょうか？ 今すぐ追加しなければならないという話ではありません(笑)

いつもありがとうございます。

from Lisedrika

**Comment by fourthline** [comment]
> 1. MabiIccoの同時発音(polyphony)はいくつですか？

96です。


> 2. 同時発音本数を超える状況が来た場合、どのようなアルゴリズムで解決しますか？

ソフトシンセサイザーの発音チャネルを増やして対応します。


> 3. 上記のスペック、アルゴリズムの駆動方式がマビノギクライアントと似ているか、同じですか？

違います。
MabiIccoはシーケンサーは1つです。
マビノギクライアントの実装は不明ですが、シーケンサー相当のものは合奏人数分あると思われます。

> 4. (番外) 同時発音数値の現況をリアルタイムでモニタリングできる機能の導入は可能でしょうか？ 今すぐ追加しなければならないという話ではありません(笑)

可能だとは思います。

**Comment by Lisedrika** [comment]
> > 1. MabiIccoの同時発音(polyphony)はいくつですか？
> 
> 96です。
> 
> > 2. 同時発音本数を超える状況が来た場合、どのようなアルゴリズムで解決しますか？
> 
> ソフトシンセサイザーの発音チャネルを増やして対応します。
> 
> > 3. 上記のスペック、アルゴリズムの駆動方式がマビノギクライアントと似ているか、同じですか？
> 
> 違います。 MabiIccoはシーケンサーは1つです。 マビノギクライアントの実装は不明ですが、シーケンサー相当のものは合奏人数分あると思われます。
> 
> > 4. (番外) 同時発音数値の現況をリアルタイムでモニタリングできる機能の導入は可能でしょうか？ 今すぐ追加しなければならないという話ではありません(笑)
> 
> 可能だとは思います。


親切なお返事ありがとうございます。

**Comment by fourthline** [comment]
> 同時発音数値の現況をリアルタイムでモニタリング

下記画像のようなイメージでどうでしょうか。
リアルタイムの状況が緑の棒グラフです。
赤の表示がこれまでの最大値です。（画像では33）

![image](https://github.com/fourthline/mmlTools/assets/1832571/54225495-7aa0-460b-92b7-63cfc6597064)

**Comment by Lisedrika** [comment]
> > 同時発音数値の現況をリアルタイムでモニタリング
> 
> 下記画像のようなイメージでどうでしょうか。 リアルタイムの状況が緑の棒グラフです。 赤の表示がこれまでの最大値です。（画像では33）
> 
> ![image](https://private-user-images.githubusercontent.com/1832571/296653363-54225495-7aa0-460b-92b7-63cfc6597064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMzU1MTcsIm5iZiI6MTcwNTMzNTIxNywicGF0aCI6Ii8xODMyNTcxLzI5NjY1MzM2My01NDIyNTQ5NS03YWEwLTQ2MGItOTJiNy02M2NmYzY1OTcwNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMTYxMzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWNlOTQ3MzAzODc3MDlkY2RkYzZmODYwOGRiOTVlY2JkMDNmNzNjYTE1NjQ4NjEyNjE0MzYwMjdkNjMyMzkwZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.45WciSBNCoQbtNwHR9hhOBIHMrgTqMqTaruOb7w66eY)

別のウィンドウで表示してくれていいですね~
追加でレベルメーターの右側にも数字で表示してほしいです。

**Comment by fourthline** [comment]
> 追加でレベルメーターの右側にも数字で表示してほしいです。

現在の値だけでよいでしょうか？

![image](https://github.com/fourthline/mmlTools/assets/1832571/cb08834e-e5ef-4134-ab85-d3669545f1c9)

**Comment by fourthline** [comment]
韓国語の翻訳は下記で問題ないでしょうか？
`다성음악 모니터`

**Comment by Lisedrika** [comment]
> 韓国語の翻訳は下記で問題ないでしょうか？ `다성음악 모니터`

동시발음 모니터
の方がもっといいと思います。

追加で下記の項目も韓国語が適用されていないのでチェックをお願いします。
- MML collection import : 자브키엘의 악보집 불러오기
- MML collection export : 자브키엘의 악보집 내보내기
- Editing by MML text : MML 텍스트 에디터

**Comment by Lisedrika** [comment]
> > 추가로 레벨 미터의 오른쪽에도 숫자로 표시해 주었으면 합니다.
> 
> 현재 값만으로 좋을까요?
> 
> ![이미지](https://private-user-images.githubusercontent.com/1832571/296932567-cb08834e-e5ef-4134-ab85-d3669545f1c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MTYxMzYsIm5iZiI6MTcwNTQxNTgzNiwicGF0aCI6Ii8xODMyNTcxLzI5NjkzMjU2Ny1jYjA4ODM0ZS1lNWVmLTQxMzQtYWI4NS1kMzY2OTU0NWYxYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMTQzNzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTU4Yjg0YTBhMjAyMGUwNzBlMGE4N2RmMWZlZjYzOGNkYzU3MDkwYWRiYTA2ZDY3ODc0YjY4NjEzNjU4ZTc5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I73HLlxwfsOFlpMXuJMZrKY8aGtDbjEVQYc9QW5WPyw)


あ、それから私が言った数字の位置はそちらではなくここです。
こんな感じなんでしょうかね？

![image](https://github.com/fourthline/mmlTools/assets/9856673/c4731b75-8ba6-422a-b7a5-e7bc3fdbdae6)

**Comment by fourthline** [comment]
ありがとうございます。
![image](https://github.com/fourthline/mmlTools/assets/1832571/6063beab-daee-4ba4-a359-3247b7e5d17d)

テストバージョン作成してみました。
#99 についても修正したバージョンです。

[v1.5.0-beta](https://fourthline.jp/mabiicco/MabiIcco-1.5.0-beta.zip)

**Comment by Lisedrika** [comment]
> ありがとうございます。 ![image](https://private-user-images.githubusercontent.com/1832571/297231696-6063beab-daee-4ba4-a359-3247b7e5d17d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0Njk4MDQsIm5iZiI6MTcwNTQ2OTUwNCwicGF0aCI6Ii8xODMyNTcxLzI5NzIzMTY5Ni02MDYzYmVhYi1kYWVlLTRiYTQtYTM1OS0zMjQ3YjdlNWQxN2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTdUMDUzMTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE1NDZkNGI3NzE5M2UyNWJhMDUzMWE4YjlkMDZiOWYxYjY4NTg4NGI2MGFjZmI2NzY5ODgyYzdlZWM1NTM3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EXFB3CZ697EFo1NozA9QAjn9StW6BDuzTuREP-WpbTY)
> 
> テストバージョン作成してみました。 #99 についても修正したバージョンです。
> 
> [v1.5.0-beta](https://fourthline.jp/mabiicco/MabiIcco-1.5.0-beta.zip)


確認してみました。 (releaseの音などを含めて)実際に出力されている同時発音の数が表示されたらいいのですが、可能でしょうか？

たとえば、リラの音は、releaseサウンドが2秒ほど残ります。 そのため、リラ一人で演奏しても同時発音の数は3つよりはるかに多いです。

**Comment by fourthline** [comment]
> 確認してみました。 (releaseの音などを含めて)実際に出力されている同時発音の数が表示されたらいいのですが、可能でしょうか？

ノートON/OFFでカウントしていました。すみません。
VoiceStatusでみるように変更してみました。
同時発音96だと足りなかったりしますか？

[v1.5.0-beta2](https://fourthline.jp/mabiicco/MabiIcco-1.5.0-beta2.zip)

**Comment by fourthline** [comment]
別件でいただいたMMLファイルなどをみると96では足りなそうなので、256に拡張したバージョンを作成しました。

[v1.5.0-beta3](https://fourthline.jp/mabiicco/MabiIcco-1.5.0-beta3.zip)

**Comment by Lisedrika** [comment]
> 別件でいただいたMMLファイルなどをみると96では足りなそうなので、256に拡張したバージョンを作成しました。
> 
> [v1.5.0-beta3](https://fourthline.jp/mabiicco/MabiIcco-1.5.0-beta3.zip)

一つ質問があります。
 MabiIccoの基本スペックが256個に拡張されましたか？ 
それとも、Polyメーターが96個+ソフトウェア的な対応まですべて含まれた数値を測定できるようになったのでしょうか？

**Comment by fourthline** [comment]
beta3はMabiIccoのスペックとして、同時発音数を256にしたものです。

**Comment by Lisedrika** [comment]
> beta3はMabiIccoのスペックとして、同時発音数を256にしたものです。

とても素敵ですね。
詳しいテストは今晩進行してみて申し上げます。

**Comment by Lisedrika** [comment]
> beta3はMabiIccoのスペックとして、同時発音数を256にしたものです。

特に問題はなさそうです。
同時発音数が増え、再生もよりスムーズになりました。

**Comment by fourthline** [comment]
[v1.5.0](https://github.com/fourthline/mmlTools/releases/tag/v1.5.0) リリースしました。

棒グラフは横向きに変更しました。
![image](https://github.com/fourthline/mmlTools/assets/1832571/d84ea955-8f7c-433b-9bc7-2cd2f8385e16)

**Comment by Lisedrika** [comment]
手動インストール バージョンは、翻訳が正常に更新されないようです。 
zip版ではよく適用されています。

**Comment by fourthline** [comment]
一度アンインストールし、再度インストールしても解決しませんか？

**Comment by Lisedrika** [comment]
> 一度アンインストールし、再度インストールしても解決しませんか？

msiインストールファイルを使用してremove mabiiccoを選択して削除処理を経た後、再インストールしたら解決されました。
ありがとうございます。
