### ISSUE TITLE
MML Spliting

### ISSUE THREAD

**Issue by Meow-Bots** [fourthline/mmlTools#101]
こんにちは、MMLのノートをいくつに分割するかを選択するオプションを追加することを提案してもよろしいでしょうか？

NAサーバーでは、「Exclude Song Part」が有効になっている場合、メロディーに最大1600ノート、ハーモニー1に1200ノート、ハーモニー2に900ノートまで書くことができます。

**Comment by fourthline** [comment]
対応済みです。
#60 #82 

![image](https://github.com/fourthline/mmlTools/assets/1832571/5de2af45-5422-490a-86d7-a3551bce68b7)

**Comment by Meow-Bots** [comment]
あ、気づいていませんでした。どうもありがとうございます。
