### ISSUE TITLE
QHD、もしくはWindows 11環境での画面割れ現象の件

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#102]
いつもお世話になっています。

QHD環境で時々画面割れ現象が報告されています。
以下は情報提供してくださった方のスクリーンショットとバグ発生時の作業です。 
でも、これがQHD環境の問題なのか、Windows 11環境まで重なって生じた問題なのかは確認が必要だと思います。
（情報提供者の場合はWindows 11+QHD環境です。）

1. 新しいトラック追加
![image](https://github.com/fourthline/mmlTools/assets/9856673/cc47dd15-b99d-4515-9dff-56e723aef120)

2. トラックにメロディを追加(他のトラックでコピーしても構わない)
![image](https://github.com/fourthline/mmlTools/assets/9856673/9ea343ae-206c-4446-a21e-9723772fecc6)

3. トラック情報変更(トラック名を入力した瞬間から症状開始)
![image](https://github.com/fourthline/mmlTools/assets/9856673/32fdc5ec-e238-46df-9e2d-66ac3eaa3efe)

4. その後はメニューを押すか、下のトラック名にマウスを当てるだけでずっと壊れる症状が続く

ご検討くださいますようお願い申し上げます。o(TヘTo)

from Lisedrika

**Comment by fourthline** [comment]
ご連絡ありがとうございます。
追加の情報がないと問題の解決は難しそうです。
- 発生頻度は高いのでしょうか？
- MabiIccoのバージョンv1.5.0でしょうか？
- 以前バージョンでは発生していなかったなどの情報はありますか？

**Comment by Lisedrika** [comment]
> ご連絡ありがとうございます。 追加の情報がないと問題の解決は難しそうです。
> 
> * 発生頻度は高いのでしょうか？
> * MabiIccoのバージョンv1.5.0でしょうか？
> * 以前バージョンでは発生していなかったなどの情報はありますか？

1.5.0以降に発生したそうです。
発生頻度は、発生するコンピュータでは 100% です。

**Comment by fourthline** [comment]
Windowsコマンドプロンプトより下記入力して、MabiIcco実行できますか？
うまくいけば問題発生時のログがとれるかもしれません。

```
set JPACKAGE_DEBUG=true
MabiIcco.exe
```

難しいようであれば別の手段もあります。

**Comment by fourthline** [comment]
ありがとうございます。
画像上には異常を特定できるログ出力はないようです😢

別の方法がないか検討してみます。
メモ: ログ減らし、コンソールモード

**Comment by fourthline** [comment]
テストバージョンを作成してみました。
[v1.5.0_d1](https://fourthline.jp/mabiicco/MabiIcco-1.5.0_d1.zip)
2つの実行ファイルが含まれています。
現象が発生するかどうかをそれぞれで確認してみてもらえないでしょうか。
- MabiIcco_1.exe: ログ減らし、コンソールモード
- MabiIcco_2.exe: ログ減らし、コンソールモード、起動オプション変更

どちらもログ画面を出すようになっています。

別のアプローチとして、下記のようなことは試せるでしょうか？
- Windowsをセーフモードで起動してMabiIccoを起動する
- 画面解像度を落としてMabiIccoを起動する

**Comment by fourthline** [comment]
Nahimicがインストールされているのであれば影響を受ける場合もあるようです。
もしあれば、無効にする手もあるようです。（効果はわかりませんが・・・）

**Comment by Lisedrika** [comment]
> テストバージョンを作成してみました。 [v1.5.0_d1](https://fourthline.jp/mabiicco/MabiIcco-1.5.0_d1.zip) 2つの実行ファイルが含まれています。 現象が発生するかどうかをそれぞれで確認してみてもらえないでしょうか。
> 
>     * MabiIcco_1.exe: ログ減らし、コンソールモード
> 
>     * MabiIcco_2.exe: ログ減らし、コンソールモード、起動オプション変更
> 
> 
> どちらもログ画面を出すようになっています。
> 
> 別のアプローチとして、下記のようなことは試せるでしょうか？
> 
>     * Windowsをセーフモードで起動してMabiIccoを起動する
> 
>     * 画面解像度を落としてMabiIccoを起動する


テスト中で、返事を待っているところです。

そして他の方からの追加情報提供がありました。
この方は4Kモニターでバグが発生したそうなので、そちらが原因の可能性が高いですね。

**Comment by fourthline** [comment]
私のPC(Win10) 上で、3840x2160 で表示させてみましたが問題は発生しませんでした。

**Comment by Lisedrika** [comment]
> 私のPC(Win10) 上で、3840x2160 で表示させてみましたが問題は発生しませんでした。

現在までは特に異常現象は観測されていないということです。

**Comment by fourthline** [comment]
異常みられないとのことなのでクローズします。
