### ISSUE TITLE
音量エディタ機能の追加改善案

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#103]
いつもお世話になっています。

音量エディタをとても大切に使っていますが、もっと便利に使いたくて追加で提案したいと思います。

音量エディタを楽器単位でも適用できるように拡張するといいと思います。
要するに、メロディー、ハーモニー1、ハーモニー2を一発で同じ形に変更するということです。
その理由は、サステイン、レガートなどの効果を入れると、音符が2~3パートに分散される場合が多いからです。
もちろん、すべての楽器に適用するようにオプションも追加していただければ最高です。

インターフェースはP、Lの下にRを作ってイメージのように入れたらどうかと思います。 
Rは Rangeの略です。(oﾟvﾟ)ノ

![image](https://github.com/fourthline/mmlTools/assets/9856673/02bb6163-d9df-4db8-b2a8-42e90cb9ce8a)

ご検討くださいますようお願い申し上げます。

from Lisedrika

**Comment by fourthline** [comment]
いつもご提案ありがとうございます。

3つのTrackがあるとしたときに。
1. Lute
2. Lute
3. Piano

Selected Part: "1. Lute" のメロディーパートのみ　（既存）
Selected instrument: "1. Lute" / "2. Lute" のメロディー,和音1,和音2 
All Instruments: "1. Lute" / "2. Lute" / "3. Piano" のメロディー,和音1,和音2 

に対して画面表示と変更反映する感じでしょうか？

Selected Track: "1. Lute" のメロディー,和音1,和音2 

もあったほうがよいでしょうか？

**Comment by Lisedrika** [comment]
> いつもご提案ありがとうございます。
> 
> 3つのTrackがあるとしたときに。
> 
>     1. Lute
> 
>     2. Lute
> 
>     3. Piano
> 
> 
> Selected Part: "1. Lute" のメロディーパートのみ　（既存） Selected instrument: "1. Lute" / "2. Lute" のメロディー,和音1,和音2 All Instruments: "1. Lute" / "2. Lute" / "3. Piano" のメロディー,和音1,和音2
> 
> に対して画面表示と変更反映する感じでしょうか？
> 
> Selected Track: "1. Lute" のメロディー,和音1,和音2
> 
> もあったほうがよいでしょうか？

私の提案で用語使用のミスがありました。 この部分の変更が必要だと思います。

- Selected Part:選択したトラックの現在のパートのみ変更(=現在の基本仕様)
- Selected Track : 選択したトラックのすべてのパートを変更 (メロディ+ハーモニー1+ハーモニー2)
- All Track : 全ての楽器の全てのパートを変更

**Comment by fourthline** [comment]
テストバージョンを作成してみました。
Pの上に配置したRボタンです。
[v1.5.0+R](https://fourthline.jp/mabiicco/MabiIcco-1.5.0+R.zip)

![image](https://github.com/fourthline/mmlTools/assets/1832571/a13d55e6-ed65-4bdd-a7a0-a5fb9c4fc682)

**Comment by fourthline** [comment]
修正版作成してみました、
[v1.5.0+R2](https://fourthline.jp/mabiicco/MabiIcco-1.5.0+R2.zip)

- RとPの間に区分線を追加
- Rボタンにツールチップを追加
- 言語対応（既存の表示設定と同じ表記）
![image](https://github.com/fourthline/mmlTools/assets/1832571/e30ac2b5-b28f-43d6-9cda-1eb6ba2402ea)

**Comment by fourthline** [comment]
[v1.5.1](https://github.com/fourthline/mmlTools/releases/tag/v1.5.1) でリリースしました。

**Comment by fourthline** [comment]
トラックの表示設定が反映できていなかったので、次回リリースで修正します。

https://github.com/fourthline/mmlTools/commit/43511b97ce8bab91cc9d897665b78e0fd951488d

**Comment by fourthline** [comment]
[v1.5.2](https://github.com/fourthline/mmlTools/releases/tag/v1.5.2) でリリースしましたので、クローズします。
