### ISSUE TITLE
ドラムノート自動整列機能に関する件

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#104]
いつもお世話になっています。

今回ご提案する新機能は、GM Standard Drum Mapをベースにしたドラムノート自動整列機能です。
現代に作られる大多数のメディアはGM Drumを仮定して作られるので、ドラムパートに限っては自動的に整列してくれる機能があれば良いと思います。
もちろん、ミディを読み込んだときから完全自動で処理すると互換性の問題があるので、何かメニューを作って必要なときだけ適用したほうがいいですね。

詳しい内容は別に整理させていただく予定ですが、企画した部分はこうです。
 1. 該当メニューやボタンを押す。
 2. マビノギドラムとGM Drumが一致しないノートを先にサーチ。
 3. 2に該当するノートをマビノギドラムの音域帯の外に移動して順次整列。
 4. マビノギドラムとGM Drumが一致するノートをサーチ(Bass Drum 1, Closed Hi-hat, etc...)。
 5. 4に該当するノートをマビノギドラムの該当位置に整列。

2と3の段階が先に先行する理由は、4の段階作業をする時に重なるノートができるからです。 
ですから、サポートしていない音を先に外に移しておいて残りの作業をすることがエラーを作りません。
えーと、そして3の段階によって外に整列されたノートは作業者たちが自ら整理するようにするものと予想しています（笑）。

GM Drum Map
![image](https://github.com/fourthline/mmlTools/assets/9856673/91151a67-8226-4b14-a6f9-531bbb84140b)

マビノギ Drum Map
![image](https://github.com/fourthline/mmlTools/assets/9856673/0187824b-d2d5-4a23-b7c3-1760e933102f)

ご検討くださいますようお願い申し上げます。

from Lisedrika

**Comment by fourthline** [comment]
ご提案ありがとうございます。

GM Drum Map -> マビノギ Drum Map の変換テーブルがあれば可能だとは思います。
私のほうでこれを作成するのは直近ではむずかしそうです。

**Comment by Lisedrika** [comment]
> ご提案ありがとうございます。
> 
> 
> 
> GM Drum Map -> マビノギ Drum Map の変換テーブルがあれば可能だとは思います。
> 
> 私のほうでこれを作成するのは直近ではむずかしそうです。

これは私が整理して差し上げればいいと思います。 ピッタリのもの以外は外に押し出せばいいですから。

**Comment by Lisedrika** [comment]
> ご提案ありがとうございます。
> 
> GM Drum Map -> マビノギ Drum Map の変換テーブルがあれば可能だとは思います。 私のほうでこれを作成するのは直近ではむずかしそうです。

[20240427_Drum map converting.xlsx](https://github.com/fourthline/mmlTools/files/15137008/20240427_Drum.map.converting.xlsx)

**Comment by fourthline** [comment]
> [20240427_Drum map converting.xlsx](https://github.com/fourthline/mmlTools/files/15137008/20240427_Drum.map.converting.xlsx)

ありがとうございます。

テスト版作成してみました。
[1.5.3+dc](https://fourthline.jp/mabiicco/MabiIcco-1.5.3+dc.zip)

- MIDI読み込み時のオプション設定にかかわらず、ドラムチャネルはオクターブ変換しないよう変更
- DLS音源使用時、MIDI読み込み時にドラムチャネルは 楽器 "ドラム" に設定するよう変更
- 編集メニューに「Drum Converting (General MIDI -> Mabi)」を追加、現在のトラックに対してのみ変換を実施します
- #105 の内容も含んでいます


![image](https://github.com/fourthline/mmlTools/assets/1832571/2716492d-54f5-4f1e-927a-ea3b47e1d9b8)

**Comment by Lisedrika** [comment]
2つの機能ともうまく機能します。 
マビノギのドラム音色の数があまりにも貧弱で、常に完璧なコンバートを実現することはできませんが、
草案をきれいに整理してくれるという機能だけでも、とても作業時間の短縮に役立ちますね。
そしてドラムの音色を自動でセットしてくれる点もとても役立ちます。

本当にありがとうございます！（=´∇｀=）

**Comment by fourthline** [comment]
ご確認ありがとうございます。

ヘルプメニューからマッピング情報もみれるようにする予定です。
![image](https://github.com/fourthline/mmlTools/assets/1832571/42a61392-4bde-4efb-9b64-e2d4d9949568)

**Comment by fourthline** [comment]
韓国語の翻訳は下記でよいでしょうか？

Drum Converting (General MIDI -> Mabi)
드럼 변환 (General MIDI -> Mabi)

Drum Converting Map
드럼 변환 맵

**Comment by fourthline** [comment]
ありがとうございます！
たいへん助かります

**Comment by Lisedrika** [comment]
> ご確認ありがとうございます。
> 
> ヘルプメニューからマッピング情報もみれるようにする予定です。 ![image](https://private-user-images.githubusercontent.com/1832571/327316461-42a61392-4bde-4efb-9b64-e2d4d9949568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDUwMTEsIm5iZiI6MTcxNTA0NDcxMSwicGF0aCI6Ii8xODMyNTcxLzMyNzMxNjQ2MS00MmE2MTM5Mi00YmRlLTRlZmItOWI2NC1lMmQ0ZDk5NDk1NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDExODMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWVjMjk1MjUzZDcwMDJlOWMzNjljYzFmNjllNDIwMzlkNTc1NzQ0MTg2NTExODY1NzA0MmNiY2EyMzQ0MDQ5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.U4omkXib1re3i3zaUGWP6cGZ35xYRVQLNSNtyXU59K0)

気が付いたら、これ······ まるでカスタマイズが可能なウィンドウのように見えますね。(„• ֊ •„)੭

**Comment by fourthline** [comment]
画面でマッピングのカスタムができるようにしますか？

**Comment by Lisedrika** [comment]
> 画面でマッピングのカスタムができるようにしますか？

そうですね。普通のユーザーならデフォルトオプションとして使いますが、私が知り合いにこのオプションについて話を持ちかけたとき、すべてのノートが対応できない部分について残念な気持ちを吐露する方がいました。(この部分は私も同意します)。

fourthline 氏さえよければ、カスタム機能+デフォルトで復旧オプションを追加すればもっと役に立つと思います。

**Comment by fourthline** [comment]
テストバージョン作成しました。
[v1.5.3+dc2](https://fourthline.jp/mabiicco/MabiIcco-1.5.3+dc2.zip)

サブメニュー化して、Map編集できるようにしています。
アンチエイリアスの設定も有効にしています。 #106 
![image](https://github.com/fourthline/mmlTools/assets/1832571/33eab1ba-6284-43a6-960b-73211903b752)
![image](https://github.com/fourthline/mmlTools/assets/1832571/41a0054c-365a-4826-8cef-efb9c17a5d65)

**Comment by Lisedrika** [comment]
![image](https://github.com/fourthline/mmlTools/assets/9856673/03159d7b-a7aa-4960-bc45-c6d88e02834f)

アンチエイリアスの部分から先に申し上げますと、完璧です。

**Comment by Lisedrika** [comment]
テストバージョンは知り合いの方にもお知らせしました。 
もし新規機能に問題が生じたらお知らせします。

**Comment by fourthline** [comment]
timeとpolyの箇所のフォントが変わってしまいましたね...
consolasあたりに変更しようかと思っています。

**Comment by Lisedrika** [comment]
[v1.5.3+dc2](https://fourthline.jp/mabiicco/MabiIcco-1.5.3+dc2.zip)

ミルキーウェイマイク(男·女)の音が正常に出ない問題が発見されました。 確認お願いします.

**Comment by fourthline** [comment]
> [v1.5.3+dc2](https://fourthline.jp/mabiicco/MabiIcco-1.5.3+dc2.zip)
> 
> ミルキーウェイマイク(男·女)の音が正常に出ない問題が発見されました。 確認お願いします.

ありがとうございます。
こちらは把握しており、次バージョンでは修正されます。

**Comment by Lisedrika** [comment]
はい、もう一つ見落とされた部分があります。 もう一度並べ替えられた楽譜にもう一度並べ替え機能を利用する場合です。 この時、既存のmabiドラムで整列されていた部分まで移動するので結果物が割れます。

解決策は2つを考えてみました。

1. マビノギドラムの範囲にあるノートは整列しないようにするチェックボックスオプション製作
: onする場合、ドラムマップでマビノギドラムの範囲に該当するノートのボタンもグレーで非活性化処理をします
: いくら何回も整列しても対応が可能です。

2. プレビューボタン作成
: 最終的に「確認」ボタンを押したときだけドラムノートが移動します。
: 実装が簡単になると予想されますが、依然としてユーザーに与えられるノートの並べ替えの機会はたった一度だけです。

**Comment by fourthline** [comment]
> もう一度並べ替えられた楽譜にもう一度並べ替え機能を利用する場合です。 

これは、マップを変更してさらに機能実行するということでしょうか。
MIDIからのインポートデータを別にもっておき、並べ替え機能ではこのインポートデータを基準に処理すれば多重実行はされなくなり、マップ変更にも追従できるようになると思います。

**Comment by Lisedrika** [comment]
> > もう一度並べ替えられた楽譜にもう一度並べ替え機能を利用する場合です。
> 
> これは、マップを変更してさらに機能実行するということでしょうか。 MIDIからのインポートデータを別にもっておき、並べ替え機能ではこのインポートデータを基準に処理すれば多重実行はされなくなり、マップ変更にも追従できるようになると思います。

とても良い方法だと思います。

**Comment by fourthline** [comment]
遅くなりましたが、テスト版作成しました。
[v1.5.4-beta1](https://fourthline.jp/mabiicco/MabiIcco-1.5.4-beta1.zip)

- MIDIからのインポートデータに基づきドラム変換を実施するよう変更。ドラムマップを変更して再度変換した場合も元のデータを基準に変換します。以前からあるMMIファイルにはインポートデータがないため、ドラム変換を実施することはできません
- ドラム変換ダイアログに統合（変換実行、変換マップ変更）。ダイアログを開いたまま再生することも可能です。

![image](https://github.com/fourthline/mmlTools/assets/1832571/901dbd65-b7b2-47a4-94c0-5686b210fced)

ご確認おねがいします。

**Comment by Lisedrika** [comment]
> 遅くなりましたが、テスト版作成しました。 [v1.5.4-beta1](https://fourthline.jp/mabiicco/MabiIcco-1.5.4-beta1.zip)
> 
> * MIDIからのインポートデータに基づきドラム変換を実施するよう変更。ドラムマップを変更して再度変換した場合も元のデータを基準に変換します。以前からあるMMIファイルにはインポートデータがないため、ドラム変換を実施することはできません
> * ドラム変換ダイアログに統合（変換実行、変換マップ変更）。ダイアログを開いたまま再生することも可能です。
> 
> ![image](https://private-user-images.githubusercontent.com/1832571/340199106-901dbd65-b7b2-47a4-94c0-5686b210fced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2Mzc4NzQsIm5iZiI6MTcxODYzNzU3NCwicGF0aCI6Ii8xODMyNTcxLzM0MDE5OTEwNi05MDFkYmQ2NS1iN2IyLTQ3YTQtOTRjMC01Njg2YjIxMGZjZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMTUxOTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2RkNWQ4YjE4YzMyZTg2NmNhYWRjMWY4OTBmYmUyMjM1ODM1OTQ2MzY4YzNiNzk0YTJmOTM4ZjkyNDU2ZDQyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u4VXjrAefMljvyl1j5_iMte06anK5sE3MkvIYIVLh8E)
> 
> ご確認おねがいします。

これはこれでいいですね。私はとても良いと思います。
窓が開いたまま楽譜再生、Ctrl+Zなどが可能になったのもとても気に入っています。 この部分は私も見落とした部分でした。

ひとつ質問があるのですが、1.5.4以降にメディアをインポートして制作されるMMIファイルは、ドラムインポートに関する情報もファイル内にずっと保存されていますか？

**Comment by fourthline** [comment]
> ひとつ質問があるのですが、1.5.4以降にMIDIをインポートして制作されるMMIファイルは、ドラムインポートに関する情報もファイル内にずっと保存されていますか？

はい。保存の対象です。

**Comment by Lisedrika** [comment]
> > ひとつ質問があるのですが、1.5.4以降にMIDIをインポートして制作されるMMIファイルは、ドラムインポートに関する情報もファイル内にずっと保存されていますか？
> 
> はい。保存の対象です。

「変換する」を翻訳する際、「변환하다」の代わりに「변환하기」に変更することをお願いし、機能的な部分は問題ありません。

最後にGMキーを表記する部分はキーナンバーとノートを一緒に表記できますか？
例えば「#35 / O0B」みたいな感じですよね。
私もキーナンバーでは一度に調べられないので···  (^▽^;)

**Comment by fourthline** [comment]
修正版作成しました。
[v1.5.4-beta2](https://fourthline.jp/mabiicco/MabiIcco-1.5.4-beta2.zip)

- ドラムマップ設定値の保存に問題があったので修正
- ドラムマップ変更時に現在値情報の更新ができていない問題を修正
- 翻訳修正
- GMキーの表記を修正

![image](https://github.com/fourthline/mmlTools/assets/1832571/78ab7baf-adfe-45a8-b92d-75280e4efb6d)

**Comment by Lisedrika** [comment]
![image](https://github.com/fourthline/mmlTools/assets/9856673/6681c83e-b763-454f-a197-8124d0e0b5fb)

何度もお願いして申し訳ありません！ この部分を大文字でお願いします (´;ω;｀)

**Comment by fourthline** [comment]
ご指摘ありがとうございます。
ほかとそろえたほうがよいですね。
修正しました。
[v1.5.4-beta3](https://fourthline.jp/mabiicco/MabiIcco-1.5.4-beta3.zip)

**Comment by Lisedrika** [comment]
> ご指摘ありがとうございます。 ほかとそろえたほうがよいですね。 修正しました。 [v1.5.4-beta3](https://fourthline.jp/mabiicco/MabiIcco-1.5.4-beta3.zip)

現時点でこの程度なら満足です。 
もし使用中に改善が必要な部分が見つかったら、次のバージョンに別途情報を提供します。

**Comment by fourthline** [comment]
[v1.5.4](https://github.com/fourthline/mmlTools/releases/tag/v1.5.4) でリリースしました。
