### ISSUE TITLE
「音程を修正」機能を「移調」機能に発展させることの件

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#105]
いつもお世話になっています。

この前にこの機能はドラムには適用されないようにパッチしていただいて役に立っています。
ただ、実際の使用において他の方向に大きな物足りなさが一つあり、改善をお願いしたいと思います。

![image](https://github.com/fourthline/mmlTools/assets/9856673/42b032c4-e500-453a-af00-6a17d476d574)

このメニューにドロップダウンメニューを一つ追加してほしいです。 
そして、「すべての楽器」、「現在の楽器」、「現在のパート」に区分して音程を移動できればと思います。
これにより、この機能は単純に全体楽器の音程修正ではなく、個別楽器の移調まで扱える編集機能を備えることになります。

オーケストラのMIDIを使って作業する方々が移調楽器によって不便をたくさん経験しているので提案します。
(今まではMabiIccoを2つ実行した後、1パートずつ作業して移していたそうです。)

ご検討くださいますようお願い申し上げます。

from Lisedrika

**Comment by fourthline** [comment]
ありがとうございます。

画像のような感じでいかがでしょうか。
選択肢が少ないのと、パフォーマンスの問題が出る恐れがあるため、ラジオボタンで設置してみました。
![image](https://github.com/fourthline/mmlTools/assets/1832571/5da7785b-c47a-4ba2-9951-bde3678a3f34)

**Comment by Lisedrika** [comment]
素敵ですね。

**Comment by fourthline** [comment]
[v1.5.4](https://github.com/fourthline/mmlTools/releases/tag/v1.5.4) でリリースしました。
