### ISSUE TITLE
韓国語インターフェースの基本フォント入れ替えるの件

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#106]
いつもお世話になっております。

日本のプログラムを韓国のウィンドウで駆動すると、昔のフォントに対応して出力される問題があります。 おそらく「dotum」に見えますが、このフォントはあまりにも昔のものなので、今では可読性が低く、文字がぼやけて見えるという問題があります。

韓国語のウィンドウでは、この問題を解決するためにずいぶん前に基本フォントが交換されました。 このフォントは「맑은 고딕」です。(Windows 10を基準に「[Malgun Gothic」という名前だと思います)
とても可読性が高く、Windowsの基本フォントでもあるので、MabiIccoの韓国語UIにもこのフォントを適用したいのですが、可能でしょうか？

もちろん韓日中英文がすべて対応可能なNoto Sans CJKなどの立派な無料フォントもありますが、私が中国語や日本語フォントの可読性については意見を出しにくいので一応韓国語の方だけを勘案して提案します。

ご検討お願いします。

from Lisedrika

**Comment by fourthline** [comment]
私のPCでは、韓国語表示のテストでは下記のようになります。
"Malgun Gothic" のように表示されますが、正しく適用されていないですか？
![image](https://github.com/fourthline/mmlTools/assets/1832571/072a00bb-20d5-48fd-96bb-98bb2efca60a)

**Comment by Lisedrika** [comment]
![image](https://github.com/fourthline/mmlTools/assets/9856673/20b5475a-d47a-454e-8df4-051f7f62616e)

メニューのテキストは、クリアなゴシックがしっかりと適用されているようです。 
それではマーカーも確認していただけますか？

**Comment by fourthline** [comment]
マーカーも描画フォントは "Malgun Gothic" となっています。
メニューとの表示差は、アンチエイリアスの有無のようです。

マーカー表示部分（その他）も文字のアンチエイリアスを有効にしようと思います。
![image](https://github.com/fourthline/mmlTools/assets/1832571/c9456c50-c6cf-4346-bd97-4db7b63db885)

**Comment by Lisedrika** [comment]
同じフォントでも、アンチエイリアスの有無で、一種の錯覚が起きたのですね。
改善後のスクリーンショットはきれいに見えてとてもいいと思います。
とても満足です！ ♡ ٩(´▽`)۶ ♡

**Comment by fourthline** [comment]
[v1.5.4](https://github.com/fourthline/mmlTools/releases/tag/v1.5.4) でリリースしました。
