### ISSUE TITLE
原因不明のエラーが発生します。

### ISSUE THREAD

**Issue by niente0109** [fourthline/mmlTools#107]
3MLEで楽譜を作ってノーツの詳細調整をMabiiccoでやっています。
「MML更新に失敗しました　Verify Error」というエラーメッセージが出力されますが、Detailボタンを押しても説明がでません。
エラーが発生するファイルを添えましたので、ご確認をお願い致します。
[Axium Crisis (3人).zip](https://github.com/fourthline/mmlTools/files/15390741/Axium.Crisis.3.zip)

**Comment by fourthline** [comment]
情報提供ありがとうございます。

`L16d+t168&d+`

テンポ分割されているノートを、L16調律符と誤って処理したようです。
修正版作成しましたので、ご確認お願いします。

[v1.5.3+i107](https://fourthline.jp/mabiicco/MabiIcco-1.5.3+i107.zip)

**Comment by niente0109** [comment]
&を消すことを忘れたのが原因だったなんて、思いつかなかったんです…
自分のミスですが、直してもらってありがとうございます！(_ _)

**Comment by fourthline** [comment]
いえ。MMLの問題ではないです。
MabiIccoが内部で処理する過程で作っているデータの問題でした。すみませんでした。
おかげでバグみつけられました、ありがとうございました！

**Comment by fourthline** [comment]
[v1.5.4](https://github.com/fourthline/mmlTools/releases/tag/v1.5.4) でリリースしました。
