### ISSUE TITLE
和音パートにテンポ指定が含まれる場合のエラー

### ISSUE THREAD

**Issue by Colimoceise** [fourthline/mmlTools#109]
和音1・2・歌パートに含まれる（入力しようとしている）テンポ指定が、メロディパートにもし置いたとしたら6tick未満の長さの音符や休符が必要になってしまう位置にあるとき、和音1・2・歌パートにテンポ指定が問題なく置けるのにかかわらずエラーが出て、編集できなくなります。
「和音にテンポ出力を許可する」オプションが有効でも無効でもおなじです。

MabiIcco内の操作で再現できる例を示します。
メロディパートの冒頭に48分音符を置き、和音1パートの冒頭から64分音符ぶん経過後の位置にテンポを入れようとしたとき、「MML@c48,r64t121;」のような結果になってほしいところですけれど、MabiIccoではエラーが出て、編集できなくなります。
![mabiicco_tempo](https://github.com/fourthline/mmlTools/assets/172665702/4e70d401-826d-440c-a43f-cd4ffb5da72f)

1.5.3でも、手持ちのいちばん古いバージョンの1.1.57でも、おなじ挙動です。

このようなエラーが出るMMLをMabiIccoに読み込んで鑑賞したいとき、「MML再生成」しないように「MML@インポート」する――つまり、先に合奏人数ぶんの空のトラックをつくってから、それぞれに「現在のトラックに上書き」でMMLをセットする、という独特な手順が必要になります。
（「新しいトラックを作成」すると「MML再生成」が働き、上記のエラーが出て読み込めません。）

「和音パートにテンポ指定を含むMMLを、MabiIccoでエラーの心配なしに読み込み・再生・再書き出しできる」ようになれば、ありがたいと思い、要望させていただきます。もちろん、編集もできるようになればいちばん良いです。
もし、MML最適化処理の部分で解決できることでなければ、明示的に「MMLを再生成しない」ように（オプションなどつけて）操作できるようにできれば、かわりの解決策になりそうだと思います。あらためて提案させていただくかもしれませんけれど、そちらは別件として切り分けることにします。

**Comment by fourthline** [comment]
対策版の確認バージョン作成しました。
[v1.5.4-beta2](https://fourthline.jp/mabiicco/MabiIcco-1.5.4-beta2.zip)

![image](https://github.com/fourthline/mmlTools/assets/1832571/43f31d53-cf92-4699-9805-44cc1158c3f0)


ご確認お願いいたします。

**Comment by fourthline** [comment]
MMLのデータありがとうございます。
読み込みできるよう修正してみました。
[v1.5.4-beta3](https://fourthline.jp/mabiicco/MabiIcco-1.5.4-beta3.zip)

- メロディのノートをまたぐテンポで6tick未満の処理を修正
- 休符中のテンポで6tick未満の処理を修正

ご確認お願いいたします。

**Comment by fourthline** [comment]
[v1.5.4](https://github.com/fourthline/mmlTools/releases/tag/v1.5.4) でリリースしました。
