### ISSUE TITLE
「分割コピー時にメロディーパートに空白を追加」機能のバグ

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#110]
いつもお世話になっています。

(楽譜製作者の力量によって差があるかもしれませんが)、和音1や和音2がメロディーよりはるかに長い上に、ザブキエル楽譜集まで必要な場合が発生することがあります。

この場合、分割コピー機能を使用すると、前部の楽譜には空白(<>)が正常に挿入されます。 しかし、メロディーパートが終わると、それ以降の楽譜には挿入されない問題があります。 したがって、後ろの部分に出力される一部の楽譜は、マビノギで正常に作ることができません。

したがって、このような場合にも使用者の利便性のために、後ろの楽譜にも無条件に空白が挿入されるように処理しなければならないと思います。

バグの再現のための簡単なサンプル楽譜を製作して添付します。 確認お願いします.

![image](https://github.com/user-attachments/assets/a88c7719-de02-430f-9a6a-a4a7f1ee3f54)

[20240717_jab_bug.zip](https://github.com/user-attachments/files/16263065/20240717_jab_bug.zip)

ご検討くださいますようお願い申し上げます。

from Lisedrika

**Comment by fourthline** [comment]
ご指摘ありがとうございます。

確認したところ、Rank表示部のみの問題のようです。
実際にMMLを出力すると、すべての分割MMLに対しても "<>" は出力される形になっているようです。

![image](https://github.com/user-attachments/assets/62b90490-1b88-4748-b2bf-a2f22c031f36)

**Comment by fourthline** [comment]
次バージョンで修正されます
![image](https://github.com/user-attachments/assets/abdeb233-391b-4d7a-a535-398cc5d5c7dc)
