### ISSUE TITLE
編集機能に関して色々…

### ISSUE THREAD

**Issue by hnhr1995** [fourthline/mmlTools#26]
Mabiicco 使ったところ、色々バグ見つけました。

１．メロディーと和音が完全に重なる時に音量が勝手に変われます。
（例えば、メロディー：V15CCCCCCCC、　和音：V15CCCCCCCC みたいな。）

２．パート入れ替えを使ってメロディーのノートを和音にコピーする時に（その逆も同じです）しばらくの間、メロディーとコピーした和音が一緒に動きます。
映像はこちらへ　http://youtu.be/UWysSryLyOs

３．バグではありませんが、各パートの判別が見難いと言う意見が多数あったので代表して言います。自分の考えですが、パート別にrectColorを変わって見るとか（例えば、メロディー：赤、和音１：緑、和音2：青　のように）、一歩進んで、パート別に色を自分で変える機能とか…まぁ、自分は適応しましたがどうやら判別が今より見易くなるといいと思います。

**Comment by fourthline** [comment]
3について。
今の設定はちょっとずつ色変えてるんですけどね。（わかりにくい）
5色 x8使用。（全トラックで設定したら x12）･･･。
ん～。（悩み）

![mabiicco_20150108](https://cloud.githubusercontent.com/assets/1832571/5663591/5a2e2368-978c-11e4-8ee4-6bc9876cb7bc.png)
上からメロディ、和音１、和音２、歌の非アクティブ時の色設定

**Comment by hnhr1995** [comment]
どれを優先するかの問題ですね。
パートの見分けか(今のもの）、トラックの見分けか（3mle、まきまびしーくのもの）
Mabiiccoではパート別に色を指定し、それをトラック別に濃さを少しずつ変えるやり方を使ってますよね…。まぁ、私の考えには、色の指定を（トラックに関わらなく）各パート別に分けて、’3mle’のように色を指定するとか’、まきまびしーく’のようにColor Picker 使って自分の好みで色を選ぶことがいいと思いますが、その過程でコードが重くなるのは避けられないんでしょうね…。

**Comment by fourthline** [comment]
1. 修正済み
2. 修正済み
3. 配色、表示影修正にて対応。（設定数が多くてどうしようかなぁ）

（参考）alpha20時点の配色です。トラックに対して色を設定、編集選択時に影付き表示としています。
![mabiicco_2015021101_color](https://cloud.githubusercontent.com/assets/1832571/6145896/fc26be0c-b229-11e4-9fb5-b39e6eafadd2.png)

ファイル個別にパート色カスタマイズの設定をつけるかなぁ。（と思案中）
配色カスタマイズについては、 #5  にもあるので　Closeとします。
