### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by Mabinogi-delight** [fourthline/mmlTools#29]
Using 7zip to compress MabiIcco folder can reduce file size by 1/3, and it is supported by most file compression software.

Even if the self-extractor is included, the file size is 32.7MB v.s. 51.1MB from zip format. 

![mabiicco](https://cloud.githubusercontent.com/assets/7549586/6979514/ba6275ea-da30-11e4-850b-4ae141b0c19d.png)

http://www.7-zip.org/

**Comment by fourthline** [comment]
I'm sorry in Japanese comments.

* alpha6 あたりは、7z self-extract だったこともあります。
* インストーラタイプだったこともあります。
* 展開時に問題になったユーザさんがいたため、現状では標準的なzipにしています。
* よい配布方法は常時思案中です。

**Comment by Mabinogi-delight** [comment]
Okay, thank you for your reply^^
