### ISSUE TITLE
Error: could not modify certain MMI file

### ISSUE THREAD

**Issue by Mabinogi-delight** [fourthline/mmlTools#30]
Please refer to this MMI:

https://www.dropbox.com/s/wxyddhx2rdqdkmb/2012B.%20%E9%99%B3%E5%93%B2%E8%81%96%20~%20%E6%96%B0%E7%91%AA%E5%A5%87%E5%90%9F%E9%81%8A%E8%A9%A9%E4%BA%BA%E5%96%AE%E6%9B%B2.mmi?dl=0

The playback is totally fine; however, the code could not be modified.

I tried to import every tracks into a new mmi file, but that did not fix the problem either.

**Comment by fourthline** [comment]
情報ありがとうございます。

エラー内容：
```
Undefined tick table: 6
```

tick 6 は持っているハズ、、（L64）
詳細な調査は また後ほど

**Comment by fourthline** [comment]
ロンカドーラ

先頭の調律指定→L32
最後のL64
```
t70l32f&f&f&f&f&f&f&f&f&f&f&f&f&f&f&f64
```

**Comment by Mabinogi-delight** [comment]
The problem seems to be fixed. Thank you very much!

**Comment by fourthline** [comment]
close.
