### ISSUE TITLE
Note velocity (V)

### ISSUE THREAD

**Issue by Mabinogi-delight** [fourthline/mmlTools#31]
![image](https://cloud.githubusercontent.com/assets/7549586/8434447/ade0e18c-1f8e-11e5-8ff1-e85daa7c6c5e.png)

After doing some tests recently, I found out that all percussive instruments (including chime) are 1dB louder than other non-percussive instruments. Also, the maximum V for percussive instruments are capped at V11.

So I believe MabiIcco needs to make some adjustments on note playback regarding note velocity. Thank you :).

**Comment by fourthline** [comment]
Mabinogi ではどうなっているかという情報があれば、とても助かります。
過去の調査で、打楽器（Mabinogi）では V11が最大らしいとのことです。
それにあわせていますが、正確な測定値はもっていません。

MabiIcco
 - percussive instruments: max V11 ( midi: v * 11 )
 - non-percussive instruments: max V15 ( midi: v * 8 )

Mabinogi
 - percussive instruments: max V11 (?)
 - non-percussive instruments: max V15

**Comment by Mabinogi-delight** [comment]
![image](https://cloud.githubusercontent.com/assets/7549586/8444549/44cf34e0-1fd5-11e5-9814-422e62dcbcce.png)
This is one of the tests I have done recently, I replaced waveforms in MSXSpirit.dls for some instruments with whistle's O5C, then made the recording. The last 3 parts are from drum, bass drum and cymbals.

After normalization, this is the reading for VU meter for percussive instruments
![image](https://cloud.githubusercontent.com/assets/7549586/8444588/c0c49ab8-1fd5-11e5-8e0a-9e5f346579a1.png)

And this is for other instruments
![image](https://cloud.githubusercontent.com/assets/7549586/8444599/d541b5c0-1fd5-11e5-9603-afcf397ae221.png)

There is an 1dB difference, or 12%.

1dB 

Therefore, in MabiIcco
percussive instruments: max V11 ( midi: v * 11 *1.12) 
non-percussive instruments: max V15 ( midi: v * 8 )

But 11*11*1.12 > 127.

So you may need to make adjustments accordingly.

**Comment by fourthline** [comment]
各グラフの縦軸の単位を教えてください。
音量、または音圧のようにみえます。あってますか？
横はVelocity（V0～V15）ですね？

**Comment by Mabinogi-delight** [comment]
Yes you are right, the verticle axis are the relative volumes

I think it is more intuitive to compare velocity from midi to velocity in Mabinogi.

I will try to make another recording and analyze using Matlab and update on this issue when I have time this weekend.

**Comment by fourthline** [comment]
* mabinogi
  * max vol.
* mabiicco
  * vol. 100 -> 115
  * percussive instruments: max V11 ( midi: v * 11 )
  * non-percussive instruments: max V15 ( midi: v * 8 )

![20150704_velocity](https://cloud.githubusercontent.com/assets/1832571/8501767/a83e118a-21e3-11e5-83aa-0ae2f89b81e2.png)

**Comment by Mabinogi-delight** [comment]
I think I have figured it out.

I made a recording for normal instrument and percussive instrument. In order to make comparisons, I modified the soundfont so that they are using the same file.

![t3x2woi1sm h0z1 v na](https://cloud.githubusercontent.com/assets/7549586/8505020/824b62e8-221f-11e5-84fb-fc13c47780b1.jpg)

Then, I imported the wave file in MATLAB and removed the noisy sections (setting them to 0)

![9g3 b tazythan g e2b u](https://cloud.githubusercontent.com/assets/7549586/8505025/a188a9c2-221f-11e5-8838-47372ca9ae62.jpg)

Then I do a numerical integration for each segment, take the squareroot, and normalize the values so that maximum velocity is 127.
![m4n2 4t8ii2 t3tkkv iqw](https://cloud.githubusercontent.com/assets/7549586/8505071/2df0046e-2220-11e5-9a79-49f93bb50fd0.jpg)

And this is the result:

![y 7o4opndzjilvar hdai](https://cloud.githubusercontent.com/assets/7549586/8505106/200d3e1a-2221-11e5-9a10-2513f5247a50.jpg)



So normal instruments: 8 * V
Percussive instruments: 12 * V (capped at 127)

**Comment by Mabinogi-delight** [comment]
I was playing back one MML from our previous concert:
https://youtu.be/nD0YkwAbQx8?t=1h33m10s

And the note velocity are kinda off to me in MabiIcco:
https://www.youtube.com/watch?v=-OnwyGyvxX4

P.S: This is what I got in 3MLE2: 
https://www.youtube.com/watch?v=tV14geT2uGo


And then I did a solo test:
https://www.youtube.com/watch?v=nFeGFMoDBsI




Soundfont:
https://www.dropbox.com/s/fuq9zw2ynrhhwsz/MSXspirit04.dls?dl=0

MML:
https://www.dropbox.com/s/ngrkd546kuqq3go/24.%20MMZX%20~%20Prometheus%20%26%20Pandora.mml?dl=0


I believe somehow you normalized the maximum level for each individual note of all instruments?

**Comment by fourthline** [comment]
is this Soundfont customized?
13="SynthDrumKit"

JP-mabinogi:
13="Bottle_A" (MSXspirit01.dls)

Because "Bottle_A" is not used so much, it is not adjusted.

**Comment by Mabinogi-delight** [comment]
Yes, it is a customized soundfont.

I believe MabiIcco normalized the loudness for each individual note while Mabinogi did not, and that is causing the differences.

![waves](https://cloud.githubusercontent.com/assets/7549586/21487750/10fa0f42-cc0d-11e6-8f53-2e4e60a5a155.png)

Note "Bass Drum" is louder in original wave file, but this is the recording from MabiIcco

![recording](https://cloud.githubusercontent.com/assets/7549586/21487767/da3dd6d6-cc0d-11e6-9a1e-d2bf44cb7b36.png)

It seems like MabiIcco found the maximum level for each individual note, then scale them to the same level. It is a feature Mabinogi should have, but they did not implement it.

**Comment by fourthline** [comment]
Mabinogi: DLSのAttenuationが効いている
MabiIcco: DLSのAttenuationが効いていない

```
Impact Hit C6
Attenuation: -07.7dB

36BassDrum1
Attenuation: 00.0dB
```

**Comment by Mabinogi-delight** [comment]
It is fixed in v29, thank you very much!
