### ISSUE TITLE
トラック制限を増やす (Increase Track Limit)

### ISSUE THREAD

**Issue by inklit** [fourthline/mmlTools#33]
## **Japanese:**
事前に貧しい日本人のために申し訳ありません。 私は英語を話しますが、Google翻訳を使用しています。

私はトラックの制限を16からもっと高い数字、おそらく32または64に上げることを要求しています。
ここで MAX_TRACK 変数を変更しても機能しません。
https://github.com/fourthline/mmlTools/blob/d870eb785a0617e667597a8008598d454b1be28c/src/fourthline/mmlTools/MMLScore.java#L38

私はトラックがメモリに追加されていると信じていますが、ここでは正しくレンダリングされていません。
https://i.imgur.com/rsu46y5.png
https://i.imgur.com/lkQpD5Q.png
画面上に16トラック以上はレンダリングされません。 16トラック以上を追加すると、色付きのアイコンが消えます。

私はあなたが助けてくれることを願っています。

## **English:**
Sorry in advance for the poor Japanese. I speak English, but I am using Google Translate.

I am requesting that the track limit be lifted from 16 to a higher number, possibly 32 or 64.
Modifying the MAX_TRACK variable here does not work.
https://github.com/fourthline/mmlTools/blob/d870eb785a0617e667597a8008598d454b1be28c/src/fourthline/mmlTools/MMLScore.java#L38

I believe the tracks are being added in memory, but they are not rendering properly here.
https://i.imgur.com/rsu46y5.png
https://i.imgur.com/lkQpD5Q.png
No more than 16 tracks render on the screen. If you add more than 16 tracks, the colored icons disappear.

I hope you can help, thanks.

**Comment by fourthline** [comment]
日本語でごめんなさい。

17番目のTrackが表示できないのは、MIDIでエラーがでているためのようです。
再生時にMIDIを使用していますが、使用しているMIDIのチャンネルが16個までです。
データとしては、32トラックでも64トラックでも作ることは可能ですが、
MIDIのチャンネルが16個までであるため、たとえ増やしても再生はできません。

**Comment by Mabinogi-delight** [comment]
Dear Fourthline:

I believe you can use different ports to open up more channels.
Each MIDI port only supports 16 channels, but you can have up to 256 ports.

**Comment by fourthline** [comment]
24トラックまで拡張済みです。v1.1.54-
さらに必要であれば、reopenしてください。

**Comment by inklit** [comment]
Thanks!
