### ISSUE TITLE
MML Code Edit Box | MMLコード編集ボックス

### ISSUE THREAD

**Issue by majorcyto** [fourthline/mmlTools#34]
## English
Hi, I am the owner of [MabiBeats](https://mabibeats.com) the English music sharing site. We are really impressed with your program and love it! We have been using a 3MLE we have been updating ourselves but your editor has many features we have wanted.

Many of our users want to switch to your program, but the only thing it is missing is a way to edit the MML Code directly. 3MLE will let you edit the code of each track directly if you want to. Could we get a MML Code Editor box option for each track?

## Japanese
申し訳ありませんが、私はこれに翻訳者を使用しています。

こんにちは、私は [MabiBeats](https://mabibeats.com) のオーナーです。英語の音楽共有サイトです。 私たちは本当にあなたのプログラムに感銘を受け、それを愛しています！ 私たちは自分自身を更新している3MLEを使用していますが、あなたのエディタには私たちが求めていた多くの機能があります。

多くのユーザーがこのプログラムに切り替える予定ですが、MMLコードを直接編集するオプションはありません。 3MLEでは、必要に応じて各トラックのコードを直接編集できます。 各トラックにMMLコードエディタボックスオプションを追加することは可能ですか？

**Comment by majorcyto** [comment]
@fourthline

**Comment by fourthline** [comment]
日本語ですみません。

MMLコードのテキストを直接編集したいという要望ですね。ありがとうございます。
私も以前は3MLEをよく使っていたので、テキストで編集したいと思っています。
編集モードの追加と、テキストエディタの機能をつくれば実現できるのではないかと思います。

**Comment by majorcyto** [comment]
それは素晴らしいだろう！

**Comment by fourthline** [comment]
[v1.2.94](https://github.com/fourthline/mmlTools/releases/tag/v1.2.94) でMMLテキスト編集の機能を追加しました。
