### ISSUE TITLE
o8b+ works in game, but not in MabiIcco

### ISSUE THREAD

**Issue by Mabinogi-delight** [fourthline/mmlTools#36]
Just like o0c- actually works in Mabinogi,
o8b+ works in Mabinogi.

Would you please fix it? Thank you very much!

**Comment by fourthline** [comment]
What instrument?

**Comment by Mabinogi-delight** [comment]
If you load a custom soundfont, and you type in o8 cdefgabb+, and you can hear notes in o9c
But o9c does not work.

MML code:

o8cdefgabb+r
o8cdefgab>cr
o8cdefgabo9cr
n96n98n100n101n103n105n107n108

https://www.youtube.com/watch?v=f5lQ7AI0y2M

**Comment by fourthline** [comment]
Mabinogi の機能にないためサポートの予定はありません。
