### ISSUE TITLE
Ctrl+C, Ctrl+V across different MabiIcco windows

### ISSUE THREAD

**Issue by Mabinogi-delight** [fourthline/mmlTools#37]
Dear Fourthline:

A lot of times I open up 2 MabiIcco WIndows during editing. 

I can use Ctrl+Shift+C, or Ctrl+Shift+V to copy/paste entire part across different MabiIcco windows,
but I cannot use Ctrl+C, Ctrl+V to copy/paste notes across different MabiIcco windows.

I am wondering if you can add that function? 

Many thanks.

**Comment by Aeronica** [comment]
Key-binds for COPY/PASTE would be very helpful!

COPY / PASTEのキーバインドはとても役に立ちます。

**Comment by fourthline** [comment]
現状できるようになっていると思うのでCloseします。(v1.2.73)
