### ISSUE TITLE
ファイル形式の改善案

### ISSUE THREAD

**Issue by logue** [fourthline/mmlTools#38]
MabinogiのMMLとMaple Story2のMMLの仕様がテンポの扱いがトラックごとである以外ほぼ同じなので、保存ファイル形式をMaple Story2でも直接読み込める.ms2mmlを拡張した形式にするのはどうでしょうか？

MapleStory2のMMLのファイル形式は以下のようなXMLになっています：
```xml
<?xml version="1.0" encoding="utf-8"?>
<ms2>
  <melody>
    <![CDATA[ ... ]>
  </melody>
  <chord index="1">
    <![CDATA[ ... ]>
  </chord>
  <chord index="2">
    <![CDATA[ ... ]>
  </chord>
  ...
</ms2>
```

ただ、この状態では当然、作者、曲名、パンポット、楽器の指定が含まれていません。そこで
```xml
<?xml version="1.0" encoding="utf-8"?>
<meta>
  <author>作者</author>
  <title>曲名</title>
  <players>
    <player index="0">
      <instrument>0</instrument>
      <voice>0</voice>
    </player>
  </players>
</meta>
<ms2>
  <melody  player="0">
    <![CDATA[ ... ]>
  </melody>
  <chord index="1"  player="0">
    <![CDATA[ ... ]>
  </chord>
  <chord index="2"  player="0">
    <![CDATA[ ... ]>
  </chord>
  <chord index="3"  player="0">
    <![CDATA[ ... ]>
  </chord>
  ...
</ms2>
```
というようにmetaタグ内に作者や曲名、各奏者の設定（使用楽器、歌）をいれて、ms2mmlファイル形式を拡張します。（この例では、MapleStory2のMMLに歌の楽譜が含まれてしまっていますが、たぶん分けたほうがいいと思います。）

こうすることで、直接MapleStory2で固有の設定を維持したままもMMLを読み込ませることができます。

**Comment by fourthline** [comment]
ご提案ありがとうございます。
MapleStory2少し試していましたが、日本でサービス終了してます😭ので確認できませんでした。
必要であればエクスポート機能かなにかでとは思いますが、対応予定ありません。
