### ISSUE TITLE
Drums still need to be updated into the system 

### ISSUE THREAD

**Issue by lavaashcrow** [fourthline/mmlTools#39]
there is new audio for Tuned Flute and Whistle, Harp Octaves ,and a new Drumset instrument that needs to be updated to the system ,  all i know is changing the DLS doesnt seem to do anything to add those in If anyone can work on this let me know thanks

**Comment by Mabinogi-delight** [comment]
What you need to do is to edit MabiIcco\properties\instrument file using notepad.

> 27=Drum Kit,N,O2F,O4F

Add this line, save the file and then reboot MabiIcco, and the drum kit will show up in the menu.

**Comment by lavaashcrow** [comment]
thanks for that
