### ISSUE TITLE
Can we add a zoom feature when im editing at 32/64 its hard to adjust the notes 

### ISSUE THREAD

**Issue by lavaashcrow** [fourthline/mmlTools#40]
and largest i can get the scale to look is 14 px

**Comment by Mabinogi-delight** [comment]
Use control+mouse wheel to zoom-in/out horizontally, doing so allows you to edit even 64th notes.

**Comment by Mabinogi-delight** [comment]
Also, that 14px is for note height, which should be plenty (My monitor is at 2560 by 1440, and I am using a note height of 10px)

**Comment by fourthline** [comment]
If you don't have a mouse wheel, you can also zoom in and out with the icon below.

![zoom in](https://raw.githubusercontent.com/fourthline/mmlTools/master/src/img/scale_up.png)
![zoom out](https://raw.githubusercontent.com/fourthline/mmlTools/master/src/img/scale_down.png)

**Comment by fourthline** [comment]
Please reopen if you have any additional questions.
