### ISSUE TITLE
Tempo(t)がメロディーのみに適用されるため、バグが発生する。

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#44]
Sample code 1 : MML@l1>ct180v0c&cv8,gggggggggggg,;
Sample code 2 : MML@l1>c&c&c,ggggt180gggggggg,;

Sample code 1はメロディーに1つの音が続いている時にテンポを180に切り替えた後、クリップボードでエキスポートしたものです。
しかし、これはバグが発生したものであり、きちんと音符が処理されているわけではありません。
Mabiiccoはメロディーにのみテンポが挿入されます。 
従って、自動的にメロディの音を後ろでv0に切ってからテンポを挿入します。

実際のMabinogiや3MLEなどでは、和音1、和音2にテンポを入れてこのような表現が可能です。
Sample code 2を参照してください。 これが私の願う形（そして実際に問題なく動く）の楽譜表現です。

このバグは、和音1、和音2にもテンポを適用できるように修正すれば解決できると思われます。

**Comment by fourthline** [comment]
Sample code 2：このMMLは以前は正しくMabinogi内で演奏できなかったが、現在は正常に再生されるようである。
Sample code 1：MabiIccoは昔のMabinogiで演奏できない問題を軽減するための出力となっているが、Mabinogi側が修正されているようなので、改善を検討する。

**Comment by Lisedrika** [comment]
> Sample code 2：このMMLは以前は正しくMabinogi内で演奏できなかったが、現在は正常に再生されるようである。
> Sample code 1：MabiIccoは昔のMabinogiで演奏できない問題を軽減するための出力となっているが、Mabinogi側が修正されているようなので、改善を検討する。

ありがとうございます。

私の予想では、各パートの音が再生されていることを確認し、それに合わせて処理する追加アルゴリズムが必要になると予想されます。
しかし、実際のゲームでは正常に認識して動作する部分なので、改善されることを期待しています。（*´▽｀*）

**Comment by fourthline** [comment]
[v1.0.42](https://github.com/fourthline/mmlTools/releases/tag/v1.0.42)で修正しました。
MML@l1.>c&c,ggggt180gggggggg,;

**Comment by Lisedrika** [comment]
> [v1.0.42](https://github.com/fourthline/mmlTools/releases/tag/v1.0.42)で修正しました。
> MML@l1.>c&c,ggggt180gggggggg,;

リリースノートと駆動方式を確認しました。 
多方面でテストしてみた結果、正常作動中のようです。
ありがとうございます。

**Comment by fourthline** [comment]
クローズします。
