### ISSUE TITLE
The volume of the instrument is not amplified when notes of the same volume and length are input to the Melody/Chord 1/Chord 2 part.

### ISSUE THREAD

**Issue by Dovidic** [fourthline/mmlTools#45]
This document was translated using Google Translate.

In MabiIcco, the volume is not amplified when notes of the same volume and length are entered for melody/chord 1/chord 2 parts. However, in Mabinogi, instrument volume amplification is normally supported except for Lute, Ukulele, Mandolin, Chalumeau, Flute, and Electric Guitar.

MML used for testing.
Melody: v15crcrc
Chord 1: v15rrcrc
Chord 2: v15rrrrc

If you play the above MML on Mabinogi, you will see that the volume is amplified 2x/3x compared to the default volume.

**Comment by fourthline** [comment]
日本のマビノギ環境おいては、音量は変わらないように聞こえました。

**Comment by Dovidic** [comment]
> 日本のマビノギ環境おいては、音量は変わらないように聞こえました。

演奏システムは、他のものと思われる。  MabiKR基準では適用されています。

**Comment by Dovidic** [comment]
他の国のクライアントにテストした結果、NA / KRは音量増幅が適用されTWは適用されません。

**Comment by Mabinogi-delight** [comment]
They are not supposed to be amplified after MusicQ update.
It may be due to "allow note overlapping" setting flag in soundfont file (MSXSpirit.dls) for each individual region of a specific instrument.

![image](https://user-images.githubusercontent.com/7549586/130313798-db196a4a-76f6-4014-8108-fd3a65b86786.png)
(This is a screenshot taken from Awave Studio).

**Comment by Dovidic** [comment]
> They are not supposed to be amplified after MusicQ update .
> It may be due to "allow note overlapping"setting flag in outdated (?) soundfont file (MSXSpirit.dls) for each individual region of a specific instrument.
> 
> ![image](https://user-images.githubusercontent.com/7549586/130313798-db196a4a-76f6-4014-8108-fd3a65b86786.png)
> (This is a screenshot taken from Awave Studio).

I checked all the tones of Msxspirit01~04.dls of the latest version of KR/TW, and it shows that only certain instruments can be amplified. Some instruments may not be able to amplify only one or two notes. I also checked the sound of the 2004/2009 version of MSXspirit.dls, and there is a slight difference in the non-amplified section.

References: https://docs.google.com/spreadsheets/d/1zIXuHBy5qg-JuD1uTCwufkvHod72NxNnYbcZFCdlcs4/edit?usp=sharing
(You may need a translator)

**Comment by Mabinogi-delight** [comment]
@Dovidic 
All instruments with "allow note overlap" flags (which agree with your Google Sheet result) should allow note amplification, which could be useful for instruments that are too quiet.

I've tried the following cases in game (CN server):

Case 1

MML@
v7CCC
,
v7CCR
,
v7CRR
;

It sounds like: 
v12Cv10Cv7C

(Actually the first note should be slightly lowder than v12), because the "loudness" is the square of "v" value, or v10 should be 4 times louder than v5.

Case 2

MML@
v7CCC
,
v7RCC
,
v7RRC
;

It actually sounds like
v7CRR

Interstingly, if you swap Melody and Chorus 2:

Case 3

MML@
v7CRR
,
v7CCR
,
v7CCC
;

It sounds like: 
v12Cv10Cv7C again!


However, this is just for solo. 

I think the solution is to use **different** v0 notes instead of R.

So, back to case 2:

MML@
v7CCC
,
v7RCC
,
v7RRC
;

if we replace R with v0C, it still behaves the same.

But if we replace R in chorus1, chorus2 with notes that are different from each other, AND not the following note,

E.g., 

MML@
v7CCC
,
v0dv7CC
,
v0eev7C
;

It sounds like: 
v12Cv10Cv7C again!

**Comment by Dovidic** [comment]
I was only going to use it to simply amplify the volume of an instrument such as a violin, and I didn't really consider how to boost the volume while using other notes. thank you for the information!

Considering the ADSR envelope in a typical ensemble score, I don't think it will ever be played with more than 48 polyphony. MML using this method performed normally in Mabinogi up to the 15th Quartet score.

**Comment by Mabinogi-delight** [comment]
In Mabinogi, it is actually impossible to surpass 48 polyphonic notes, or 3 per person.

Instruments like Lyre or Chime has long release time (4s and 8.033s respectively), if you write notes such as L32 ceg>ceg>ceg ...
you should notice note cut-offs (or ending early), and no matter how you arrange notes, a maximum of 3 notes will persist.

Also, in general midi, channel 10 is reserved for drum sets, but drum kits in Mabinogi actually are not drum sets in sound font file . I have not tried 16 person ensemble (because it would be very hard to test, and I was suspecting the maximum number of players that can make sound is actually 15), therefore my MMLs are up to 15 players as well. But please correct me on this if I am wrong.

**Comment by Dovidic** [comment]
Up to the 16th Quartet is playing normally. The current Mabinogi playing system seems to be separate from DirectMusic, but I don't know about other than that.
I understood the polyphony limit of 3 per person after reading this article. In fact, when I played an instrument with a high release rate, I felt the notes cut off.
What I was talking about was a situation in which notes were not played at all when playing instruments with high release rates during ensembles.

**Comment by Mabinogi-delight** [comment]
Yes I noticed that as well, especially L64 notes used in Hand Chimes.

**Comment by Dovidic** [comment]
No, it is an instrument with a very long release rate, such as the piano, harp, lyre, and handbell. This is the reason why sheet music that was impossible to play in the past (when applying for ensembles of up to 5-8 people) seems to play well after MusicQ. I understand that notes are limited to a maximum of 3 polyphony per person and that the total must not exceed 48.

**Comment by Mabinogi-delight** [comment]
Oh I see what you are saying. 
They did not put a limit on how many polyphonic notes per instrument could have before, therefore long notes (especially harp, the recording wave files had very very long blank portion by the end, more than 10 seconds), will exhaust 48 polyphonies very quickly, that made some notes afterwards not playing at all.

Still, the best solution for devCat is actually increase 48 to something like 250 or even 500, but I believe they did not know they could increase such limit.

**Comment by Dovidic** [comment]
The release rate was modified to 8.000s by extracting the square wave tone inside the Windows default MIDI sound source (gm.dls). This tone has been ported to Lute in MSXspirit01.dls.
"MML@t128v15l64<<ceg>ceg>ceg>ceg>c,,;" was played on MabiIcco and Mabinogi respectively using MSXspirit01.dls with that voice applied.

![icco_square](https://user-images.githubusercontent.com/88671533/130395415-9af1d89e-f70e-4df3-842e-f7e8e72d3829.png)
(waveform of MabiIcco)

![mabi_square](https://user-images.githubusercontent.com/88671533/130395474-16317506-e817-44b3-9617-17a48f1da3ae.png)
(waveform of Mabinogi)

Above are the waveforms from MabiIcco and Mabinogi respectively. There is no break in notes, but it is questionable whether the number of polyphony is really limited to 3 per person. 

The same results were seen with the harps with the same release rate.

![icco_harp](https://user-images.githubusercontent.com/88671533/130396001-63687714-79f4-40bb-904e-01ffc94254d7.png)
(waveform of MabiIcco)

![mabi_harp](https://user-images.githubusercontent.com/88671533/130396056-c6a327c5-81c6-4f28-ac46-cb4f4eadf286.png)
(waveform of Mabinogi)

**Comment by Mabinogi-delight** [comment]
Interesting, I did the testing earlier as well, and it seems like we are not experiencing polyphonic issue anymore, but I only tested solo mode as well.
![image](https://user-images.githubusercontent.com/7549586/130594105-e161d396-5b00-44bc-911a-c59928c09706.png)

I am using a pure 440Hz sine wave (for o3A), and this is the testing code: L

16V15o2c1r1 cc+dd+eff+gg+aa+b > cc+dd+eff+gg+aa+b > cc+dd+eff+gg+aa+b > cc+dd+eff+gg+aa+b > cc+dd+eff+gg+aa+b

And this is the testing SoundFont that can be placed in Mabinogi/mp3 folder directly (instruments: lute, chime)
[SineTest.zip](https://github.com/fourthline/mmlTools/files/7038180/SineTest.zip)

**Comment by Dovidic** [comment]
It seems that the same result can be confirmed when performing ensemble.  Except for the problem when there are more than 16 people, I don't think there is any problem due to the Polyphony limit.  Note clipping problem is presumed to be a client bug.
Tested video(from 01:44): https://youtu.be/JYfroKLkj94

**Comment by fourthline** [comment]
I created a test version.
Unzip the attachment and place the exe file in the same folder as "MabiIcco.exe" (v1.0.46).
[MabiIcco_47.zip](https://github.com/fourthline/mmlTools/files/7167848/MabiIcco_47.zip)

**Comment by fourthline** [comment]
楽器によって違うよう・・・？
2021/09/15 Mabi JP
・リュート→効果なし
・ウクレレ→効果なし
・マンドリン→効果なし
・ホイッスル→効果あり
・ロンカドーラ→効果あり
・フルート→効果なし
・シャリュモー→効果なし
・ピシスチューバ→効果あり
・リラ→効果あり
・エレキギター→効果なし
・ピアノ→効果あり
・バイオリン→効果あり
・チェロ(o2)→効果あり
・ハープ→効果あり
・チューニングバイオリン→効果あり
・チューニングチェロ(o2)→効果あり
・ドラム→効果あり
・お祭りリュート→効果あり
・お祭りウクレレ→効果あり
・お祭りマンドリン→効果あり
・お祭りホイッスル→効果あり
・お祭りフルート→効果あり
・チューニングフルート→効果あり
・チューニングホイッスル→効果あり

**Comment by Dovidic** [comment]
> 楽器によって違うよう· · ·?
> 2021년 9월 15일 MABI JP
> ·リュート→効果なし
> ·ウクレレ→効果なし
> ·マンドリン→効果なし
> ·ホイッスル→効果あり
> ·ロンカドーラ→効果あり
> ·フルート→効果なし
> ·シャリュモー→効果なし
> ·ピシスチューバ→効果あり
> ·リラ→効果あり
> ·エレキギター→効果なし
> ·ピアノ→効果あり
> ·バイオリン→効果あり
> ·チェロ(O2) →効果あり
> ·ハープ→効果あり
> ·チューニングバイオリン→効果あり
> ·チューニングチェロ( O2) →効果あり
> ·ドラム→効果あり
> ·お祭りリュート→効果あり
> ·お祭りウクレレ→効果あり
> ·お祭りマンドリン→効果あり
> ·お祭りホイッスル→効果あり
> ·お祭りフルート→効果あり
> ·チューニングフルート→効果あり
> ·チューニングホイッスル→効果あり

下部のシートをご覧ください。

https://docs.google.com/spreadsheets/d/1zIXuHBy5qg-JuD1uTCwufkvHod72NxNnYbcZFCdlcs4/edit?usp=sharing

アップロードされたテストバージョンでは、すべての楽器に音量増幅がされていることを確認しました。DLS内部設定に基づいて音符重ね状況が決定されるが、この設定を適用することができますか？

**Comment by fourthline** [comment]
ありがとうございます。
リュートでも o3 だと効果ありでした。
DLS内部設定に依存しているようですね。
 >> lute_e2 0 → 効果なし
 >> lute_e3 0 → 効果なし 
 >> lute_e4 0  → 効果なし
 >> lute_e1 1  → 効果あり

**Comment by Dovidic** [comment]
> ありがとうございます。
> リュートでも o3 だと効果ありでした。
> DLS内部設定に依存しているようですね。
> 
> > > lute_e2 0 → 効果なし
> > > lute_e3 0 → 効果なし
> > > lute_e4 0  → 効果なし
> > > lute_e1 1  → 効果あり

そうです。した楽器の音色ごとに設定が異なるため、音の重なりを一括適用すると、MML作成時の誤解をもたらすことができるとします。

**Comment by fourthline** [comment]
DLS内部設定に応じて音の重なりを適用するよう修正してみました。

修正サンプルプログラムを作成してみました。
[MabiIcco_48.zip](https://github.com/fourthline/mmlTools/files/7184459/MabiIcco_48.zip)

展開して、中のexeファイルを "MabiIcco.exe"(v1.0.46) と同じフォルダに配置してください。

**Comment by Dovidic** [comment]
> DLS内部設定に応じて音の重なりを適用するよう修正してみました。
> 
> 修正サンプルプログラムを作成してみました。
> [MabiIcco_48.zip](https://github.com/fourthline/mmlTools/files/7184459/MabiIcco_48.zip)
> 
> 展開して、中のexeファイルを "MabiIcco.exe"(v1.0.46) と同じフォルダに配置してください。

ファイルありがとうございます。

すべての楽器のテストを完了し、通常の動作確認しました！

**Comment by Dovidic** [comment]
音符重ね、このUIに反映されたことについての説明が必要です。

ピアノロールに縦線で音符重ね/音符重ね不可/音域以外などの表現をしたことをよく知っているがDLSについてよく知らない場合は、縦の線が表現するのが何なのか知ることができません。

**Comment by fourthline** [comment]
UIについて、[使い方](https://github.com/fourthline/mmlTools/wiki/%E4%BD%BF%E3%81%84%E6%96%B9/4f68ab1d9caafb67bb8904bc2a339a20ba0898dc#%E3%82%AD%E3%83%BC%E3%83%9C%E3%83%BC%E3%83%89%E8%A1%A8%E7%A4%BA%E3%81%AE%E3%83%A9%E3%82%A4%E3%83%B3%E8%89%B2%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6-v1049%E4%BB%A5%E9%99%8D) に記載しています。

**Comment by Dovidic** [comment]
> UIについて、[使い方](https://github.com/fourthline/mmlTools/wiki/%E4%BD%BF%E3%81%84%E6%96%B9/4f68ab1d9caafb67bb8904bc2a339a20ba0898dc#%E3%82%AD%E3%83%BC%E3%83%9C%E3%83%BC%E3%83%89%E8%A1%A8%E7%A4%BA%E3%81%AE%E3%83%A9%E3%82%A4%E3%83%B3%E8%89%B2%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6-v1049%E4%BB%A5%E9%99%8D) に記載しています。
Note overlapの設定に関係なく、すべての楽器で同じ音高の音符を同時に演奏すると、音量が増幅されます。

**Comment by fourthline** [comment]
[v1.2.94](https://github.com/fourthline/mmlTools/releases/tag/v1.2.94) で音源のoverlapに関わらず、on/offできる設定を追加しました。
