### ISSUE TITLE
Support for dotted notes and tick table 3/3(128th notes length)?

### ISSUE THREAD

**Issue by Dovidic** [fourthline/mmlTools#46]
This document was translated using Google Translate.

Mabinogi supports dotted 64th note input and output, but MabiIcco only supports up to 64th quarter note input. Also, when MML with dotted 64 notes is loaded from MabiIcco, an Undefined tick table: 3/3 error message is output when an attempt is made to edit in dotted 64-note intervals.

![image](https://user-images.githubusercontent.com/88671533/128739653-7a10166f-2b29-41a0-bcca-4c0d4d7929c0.png)

**Comment by fourthline** [comment]
"L64." ノートは解釈可能です。（tick = 9）
MMLの全体がわかりませんが、画像のエラーは他の要因と思います。

**Comment by Dovidic** [comment]
L64. 入力のサポートは可能ですか？
演奏に使用したMMLは、以下のリンクにあります。  （最後のパートです）

https://www.dropbox.com/s/15ssaw5z743nyos/13%E2%98%85_Tappy%20-%20Shooting%20Starlight_rev2.mmi?dl=0

**Comment by fourthline** [comment]
L64. 入力のサポートは可能です。
ファイルありがとうございます。
MabiIcco-1.0.41 では編集はできました。
ただ、非常に細かいので編集内容によってはエラーになることはあると思います。
tick = 3 は L128
