### ISSUE TITLE
Split copyの使用時にメロディーパートが空白になる問題

### ISSUE THREAD

**Issue by Dovidic** [fourthline/mmlTools#47]
Music book of Jabchielを活用するためにMabiIccoに対応する機能を利用する際メロディパートの文字数が少なく和音1 /和音2パートの文字数が多い場合（ex：2300/2200/1300のMMLをSplit copy使用時1200/800  / 500、1100/800/500、0/600/300に分割）メロディパートの文字が空白になります。 
マビノギで作曲スキル使用時メロディパートが空白の場合、エラーメッセージを出力し、楽譜の作成がされていません。 メロディパートのMMLと関連のない文字を山に追加すると、楽譜作成が可能です。

**Comment by fourthline** [comment]
Music bookに限らず、通常楽譜に対する作曲スキル使用でもメロディーパートがないとMabinogi内では怒られるよう。

**Comment by Dovidic** [comment]
> Music bookに限らず、通常楽譜に対する作曲スキル使用でもメロディーパートがないとMabinogi内では怒られるよう。

正確です。 この機能を使用して分割した楽譜を作曲スキルに貼り付けようとしたときに、少し不便でした。

**Comment by fourthline** [comment]
1文字のスペースを入れるのはどうでしょうか？
MML@ ,aaa,aaa;

**Comment by Dovidic** [comment]
> 1文字のスペースを入れるのはどうでしょうか？
> MML@ ,aaa,aaa;

最も適切な対策だと思います！

**Comment by fourthline** [comment]
スペースだとMML外の文字になってしまうので、'r' をいれたいと思います。
MML@r,aaa,aaa;

**Comment by Dovidic** [comment]
> スペースだとMML外の文字になってしまうので'R'をいれたいと思います.
> MML @ R, AAA, AAA;

もはや入る文字がないからRも適切な選択に見えますが、演奏時間がRだけ長くなると思われます。  xなどの文字を入力すると、演奏時間の問題で解決することができます。
ex)MML@x,aaa,aaa; or MML@-,aaa,aaa;

**Comment by fourthline** [comment]
たしかに、Rだと演奏時間伸びますね。
もう少し検討します。

**Comment by fourthline** [comment]
デフォルトを "<>" として、設定で変更できるようしてみました。
MML@<>,aaa,aaa;

**Comment by Dovidic** [comment]
v1.0.42でその機能がデフォルトで無効になっているようです。

**Comment by Dovidic** [comment]
> 差し替えしたので再度ダウンロードしてください

通常の動作確認しました。ありがとうございます！
