### ISSUE TITLE
いくつかのバグ修正。 

### ISSUE THREAD

**Issue by narusekiya** [fourthline/mmlTools#53]
zh言語システムでは、「繁体字」と「簡体字」が分離されています。
提出してみたところ、間違いがあったので修正して分割しました。
地域関係で用途が少し違っています。
メンテナンス用です。
どうもありがとうございました。
appResource_zh_cn.properties by delight
appResource_zh_tw.properties by me
[properties.zip](https://github.com/fourthline/mmlTools/files/7198950/properties.zip)

**Comment by fourthline** [comment]
ありがとうございます。
そのまま配置してみました。

https://github.com/fourthline/mmlTools/commit/463f539bfd8398db9872595df6a13bff573bf70b
