### ISSUE TITLE
タイプミス修正依頼

### ISSUE THREAD

**Issue by Dovidic** [fourthline/mmlTools#57]
設定ファイルを翻訳中に誤って作成された部分があります。

properties/appResource_ko.properties
https://github.com/fourthline/mmlTools/blob/32a017be288d2df1164cc857c0bf5f4a043e14b3/properties/appResource_ko.properties#L246
scale_color.db_major=올림다 장조, 내림나 장조, 올림가 단조, 내림나 단조(X)
->scale_color.db_major=올림다 장조, 내림라 장조, 올림가 단조, 내림나 단조(O)

ご不便をお掛けします。

**Comment by fourthline** [comment]
ありがとうございます。取り込みました。
