### ISSUE TITLE
ロゴ、アイコン、ローディング画面

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#59]
Mabiiccoのロゴとプログラムアイコン、ロード画面を挿入する計画はありますか？ もしそうなら、私がデザインをお手伝いしますよ。

**Comment by Lisedrika** [comment]
> ありがとうございます。 アイコン：32 x 32px ロード画面：300 x 222px （現在のサイズですが、変更も可能です）

作業中です。
できあがったらここに載せておきます

**Comment by Lisedrika** [comment]
[MabiIcco Design.zip](https://github.com/fourthline/mmlTools/files/8175216/MabiIcco.Design.zip)

お待たせしました。
ローディング画面、アイコンをお届けします。

ローディング画面は背景色がなく透明です。
アイコンは32x32pxと256x256pxの2種類で、背景色もデザインに含まれるそうです。

ロゴに使用されたフォントはdinbolです。（無料フォントです）
デザインの変更について要請事項がありましたらおっしゃってください。

**Comment by fourthline** [comment]
とても素敵な画像ありがとうございます。
まずは取り込んでみたいと思います。

**Comment by fourthline** [comment]
[v1.1.63](https://github.com/fourthline/mmlTools/releases/tag/v1.1.63) で取り込んでみました

**Comment by Lisedrika** [comment]
> [v1.1.63](https://github.com/fourthline/mmlTools/releases/tag/v1.1.63) で取り込んでみました

帰宅しました。すぐ確認します。

**Comment by Lisedrika** [comment]
異常ありません！

イラストはNyx(@00nyx)さんが作業していただきました。
名前は「マビコチャン」です。
マビコチャン…かわいい…  'ㅅ')b

**Comment by fourthline** [comment]
ありがとうございます
かわいいです❤️
