### ISSUE TITLE
再生中のトラック変更時のMMLボイス適用エラー

### ISSUE THREAD

**Issue by Dovidic** [fourthline/mmlTools#63]
mmiファイルのロード後に再生中にトラックの順序を変更したときに、変更されたトラックの順序で変更前のMMLを再生しています。

ex）A B C D E F Gトラックを再生中にFトラックをBトラックの前に配置してA F B C D E Gトラック順に再生すると、ボイスチェンジは通常A F B C D E Gシーケンスに適用されますが、MMLはそのままA B C D E F Gトラックで再生されます。 停止後に再度再生すると、MML も通常 A F B C D E G 順に再生されます。

**Comment by fourthline** [comment]
ありがとうございます。
修正の検討します。
再生中はトラックの順序変更禁止にしたいと思います。

**Comment by fourthline** [comment]
[v1.1.63](https://github.com/fourthline/mmlTools/releases/tag/v1.1.63) で反映してみました。

**Comment by Dovidic** [comment]
正常動作確認しました。 ありがとうございます！
