### ISSUE TITLE
「同じ高さの音をすべて選択」機能を追加

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#64]
これは商用DAWでよく見られる機能です。
マウスを右クリックするときに出てくるメニューの中で、追加するといいと思います。

当該機能を追加する場合、特定の音を一括で修正しなければならない状況に便利です。
特にドラムパートを編集するときに役立ちます。

**Comment by fourthline** [comment]
[v1.1.63](https://github.com/fourthline/mmlTools/releases/tag/v1.1.63) で追加してみました。

**Comment by Lisedrika** [comment]
> [v1.1.63](https://github.com/fourthline/mmlTools/releases/tag/v1.1.63) で追加してみました。

すぐ確認しま-す。

**Comment by Lisedrika** [comment]
異常ありません！
