### ISSUE TITLE
MMIファイル拡張子接続 (=基本プログラムに設定)

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#65]
プログラムメニュー内に「MMIファイル接続」を追加して、
最新バージョンのMabiIccoと拡張子を簡単に接続できればと思います。

通常、圧縮プログラムやイメージビューアーにある機能ですね。 これは。

**Comment by fourthline** [comment]
管理者権限が必要なので、インストーラ形式で作成してみました。
[MabiIcco-1.2.68.msi](https://github.com/fourthline/mmlTools/releases/download/v1.2.68/MabiIcco-1.2.68.msi)

**Comment by fourthline** [comment]
msiのインストーラ形式をご利用ください。
継続してリリースしていきます。
