### ISSUE TITLE
翻訳エラーを修正

### ISSUE THREAD

**Issue by Dovidic** [fourthline/mmlTools#66]
韓国語翻訳 一部エラーがあり訂正要請いたします。

https://github.com/fourthline/mmlTools/blob/0b977b65873555ebd3007aec3c0dcf5d62bc1e84/properties/appResource_ko.properties#L203

MML 출력 옵션(악기부: 멜로디, 화음1, 화음2) -> MML 출력 옵션(악기 파트: 멜로디, 화음1, 화음2)

https://github.com/fourthline/mmlTools/blob/0b977b65873555ebd3007aec3c0dcf5d62bc1e84/properties/appResource_ko.properties#L204

MMML 출력 옵션(가부: 노래) -> MML 출력 옵션(노래 파트: 노래, 환상의 코러스)

https://github.com/fourthline/mmlTools/blob/0b977b65873555ebd3007aec3c0dcf5d62bc1e84/properties/appResource_ko.properties#L132

현재 트랙의 악기 부분 시작 위치로 설정 -> 현재 트랙의 악기 파트 시작 위치로 설정

https://github.com/fourthline/mmlTools/blob/0b977b65873555ebd3007aec3c0dcf5d62bc1e84/properties/appResource_ko.properties#L133

현재 트랙의 노래부 시작 위치로 설정 -> 현재 트랙의 노래 파트 시작 위치로 설정

曲パーツは幻のコーラスも該当する部分なので任意に追加しておきました。

startoffsetは、現在の合弁システムには意味がないと考えています。 delay 部分だけが実際の合奏に影響を与えます。

**Comment by fourthline** [comment]
ありがとうございます。
