### ISSUE TITLE
トラック複製機能のバグ

### ISSUE THREAD

**Issue by Dovidic** [fourthline/mmlTools#67]
この機能を使用すると、トラックはコピーされ、音も複製された分だけ音量が増加しますが、トラック数は増加しないように見えます。
この状態でファイルを保存して再度読み込むと、トラックは複製されます。

トラックを複製した後、トラックを再生してMMLを入力すると正しく表示されます。 その後、元に戻す（Ctrl + Z）を入力すると、トラックの複製も同時に元に戻されます。

実際の適用映像も添付します。

https://youtu.be/vcEsx52sKhM

**Comment by fourthline** [comment]
ありがとうございます。修正します。

**Comment by fourthline** [comment]
修正をv1.2.70へ反映しました。
下記からダウンロード可能ですか？
[https://fourthline.jp/mabiicco/](https://fourthline.jp/mabiicco/)

**Comment by Dovidic** [comment]
> 修正をv1.2.70へ反映しました。 下記からダウンロード可能ですか？ https://fourthline.jp/mabiicco/

機能正常動作確認しました。 ありがとうございます！
