### ISSUE TITLE
冗長なテンポ配置

### ISSUE THREAD

**Issue by mabi-foo** [fourthline/mmlTools#68]
v1.1.62まではできていたのですが、連続した同じテンポ値の配置を許容するようにしてほしいです。
T120L4CCCCT120CCCCT120CCCC

v1.1.63以降では同じテンポ値を配置することができません。
T120L4CCCC■CCCC□CCCC
■と□の部分にT120が入れられない

■でテンポを変更して□で戻す（■と□を先に配置しておいて■だけ変更する）、
といった使い方をしたいというのが要望の理由です。

**Comment by fourthline** [comment]
v1.2.73でリリースします

**Comment by mabi-foo** [comment]
v1.1.62以前と同じように配置できることを確認しました。
ご対応ありがとうございました。
