### ISSUE TITLE
Allow start octave to be configurable

### ISSUE THREAD

**Issue by kernighan** [fourthline/mmlTools#71]
Hi,

I play a game called "Archeage" that also supports MML.  However, its default octave for middle C is 5, whereas I believe for Mabinogi the starting octave for middle C is 4.  I would love to use this utility for Archeage (I also need issue #34 to do direct editing), and it would be awesome if it was possible via a preference option to change which octave middle C is represented as.

**Comment by fourthline** [comment]
MML for Mabinogi is one octave lower than other environments. I think you should do a conversion that raises the octave as a whole. In order to support ArcheAge's MML, many more issues need to be resolved.
