### ISSUE TITLE
Allow export of entire song

### ISSUE THREAD

**Issue by kernighan** [fourthline/mmlTools#72]
For multi-track songs, it should be possible to export all of them into the clip board, not a just a single track at a time.

**Comment by fourthline** [comment]
For Mabinogi, I think a single track MML output is sufficient.

**Comment by kernighan** [comment]
As I noted, there are uses for this software if it can be written properly that would make it usable to people in other games as well.  Since Archeage allows multiple tracks per instrument (up to 10 tracks @ 5k total notes), being able to export multiple tracks at once is essential. You are also competing with 3MLE, which even though it is years old already supports this as a stock option.

**Comment by fourthline** [comment]
This function is unnecessary in the Mabinogi environment. More issues need to be resolved to support ArcheAge's MML.

**Comment by fourthline** [comment]
I tried adding functions for ArcheAge to MabiIcco in v1.2.82.

- Setup -> Change sound source environment -> For ArcheAge
- File -> Export -> Export as MML for ArcheAge
