### ISSUE TITLE
Make difficulty rating configurable

### ISSUE THREAD

**Issue by kernighan** [fourthline/mmlTools#73]
In Archeage, it's possible (currently) to have 5000 notes per piece of music with up to 10 total tracks.  It would be nice to make the difficulty rating adjustable.

**Comment by fourthline** [comment]
What "make the difficulty rating adjustable" ?
If there are 10 tracks and 5000 notes in total, there is no problem.

**Comment by kernighan** [comment]
I'm talking about the "rank" values displayed in the software.

**Comment by fourthline** [comment]
There are no plans to support Archeage MML. There are also several other challenges.
