### ISSUE TITLE
Allow the ability to pick which tracks to import from a MIDI

### ISSUE THREAD

**Issue by kernighan** [fourthline/mmlTools#74]
When importing a MIDI file, it should be possible to select which track(s) to import.

**Comment by fourthline** [comment]
When importing a file, you can now select the tracks you want to import.
![image](https://user-images.githubusercontent.com/1832571/180585250-9f112fa3-3f07-474c-b52d-6c56fb8d53fa.png)

**Comment by kernighan** [comment]
Awesome, thanks!

**Comment by fourthline** [comment]
If there is no problem, I will close it.
