### ISSUE TITLE
When importing a MIDI, "track 1" remains

### ISSUE THREAD

**Issue by kernighan** [fourthline/mmlTools#75]
When I import a MIDI file, the default "track 1" remains in the editor, and then I have to manually remove it.  When importing from a MIDI, it should (probably by default) only have tracks after import that reflect the imported MIDI tracks, and not extraneous tracks from prior to import.

**Comment by fourthline** [comment]
The import function is a specification that adds data to the current Score.

**Comment by kernighan** [comment]
When would it ever make sense that you would want to keep the default track 1 when importing a MIDI?  I'd at least make that behavior optional

**Comment by fourthline** [comment]
The import keeps the existing score information and reads additionally. If you don't need "Track1", you can use the Open function.

**Comment by fourthline** [comment]
If importing into an empty score, change it to remove existing tracks.

**Comment by fourthline** [comment]
Released in v1.2.80
