### ISSUE TITLE
Changing the time of a piece of music breaks the display

### ISSUE THREAD

**Issue by kernighan** [fourthline/mmlTools#76]
If I import a MIDI done in 6/8 time, it is shown as 4/4 time.  If I then change the properties to be 6/8 time, much of the UI breaks (including the window to change the properties).  If one can manage to get that window closed, the window displaying the imported track is also broken (showing overlaying tracks) and requires resizing the window to fix the display.

**Comment by fourthline** [comment]
A simple 6/8 time signature MIDI import was fine. I think there are other problems.

**Comment by kernighan** [comment]
Let me explain better.  I import a MIDI that is in 6/8.  The program however sets the timing to 4/4.  I then go into the properties via the file menu to change it to 6/8 time so the measures line up correctly, at which point the program windows get all messed up.

**Comment by kernighan** [comment]
![Property1](https://user-images.githubusercontent.com/1541600/181113318-b325fef6-2a33-496d-9cda-74836cf08837.png)
![property2](https://user-images.githubusercontent.com/1541600/181113327-ece1d6d9-af91-4bb5-92a1-6bab22c50580.png)
![property3](https://user-images.githubusercontent.com/1541600/181113329-639c9be6-f992-4677-88f8-7ad26d79f81e.png)

**Comment by kernighan** [comment]
Attached screenshots of the problem

**Comment by fourthline** [comment]
Thank you for your detailed explanation.
From the screenshot image it looks like there is some kind of problem.
But the MIDI data I have can't cause similar problems, so I need real data.

**Comment by fourthline** [comment]
I can't debug it with the information I have now.  Additional information required.
