### ISSUE TITLE
Tuplets are not converted correctly from MIDI

### ISSUE THREAD

**Issue by kernighan** [fourthline/mmlTools#77]
If importing a MIDI that various tuplets, the values used are incorrect.  For example, an 8th note triplet should be a length of 12.  So what I would expect for an 8th note triplet of: 'ede' would be:

e12d12e12

But what gets generated is:

l16e19.d.e19.

This doesn't even sum up to a valid value, is it is longer than a quarter note, and will cause de-syncs in the music.

**Comment by fourthline** [comment]
It cannot be done because it is aligned with L64. Most data will be unreadable without alignment.

**Comment by kernighan** [comment]
This is a factually false statement.  3MLE is able to import tuplets that while not entirely correct at 64th quantization at least are correct in total length.  an 8th note triplet is supposed to take the same time as a quarter note.  Your current code is *longer* than a quarter note, making the import literally break the ability to keep tracks in sync.

**Comment by fourthline** [comment]
L64 = 6tick (Resolution 96)
triplet L12 = 32tick (Resolution 96)
32 / 6 = 5.3333333.....
![image](https://user-images.githubusercontent.com/1832571/181878051-aa878977-0a3e-4cea-b080-06f5d9838a7b.png)

**Comment by fourthline** [comment]
Even the version of 3MLE I have on my PC has L64 alignment, so I can't seem to import triplets in L12 representation.
![image](https://user-images.githubusercontent.com/1832571/183275669-632e8ff8-4e49-4395-968a-0df12fde8698.png)

**Comment by Lisedrika** [comment]
> This is a factually false statement. 3MLE is able to import tuplets that while not entirely correct at 64th quantization at least are correct in total length. an 8th note triplet is supposed to take the same time as a quarter note. Your current code is _longer_ than a quarter note, making the import literally break the ability to keep tracks in sync.

If the tool doesn't convert triplet perfectly, it doesn't mean anything.
It only adds to the annoyance of editing. :(

**Comment by Mabinogi-delight** [comment]
I can understand the frustration but I know exactly why it happens.

The real issue is that, when converting from MIDI to MML, some midis (or tracks) are not perfectly quantized. Since a 64th note is only 6ticks (under 96TPQN condition),  while a 48th note is 8 ticks. Some tracks can have an offset of 2~3 ticks (especially for instruments with longer attacks, like string instruments), if tuplets are allowed, we need to find a way to solve this issue.

Currently, what I am doing with midi files with large amount of tuplets, is to scale note length by 1.5 or 0.75 to get rid of 1/3 factors in note length, and make adjustments accordingly.

As for MabiIcco, I can think of two ways to improve (that will require a lot of hard works from Fourthline of course).

First way is to have a separate option to convert tuplets while importing midi. However, prior to converting, midi files needs to be quantized correctly, and starting time for each track need to be aligned to proper resolution (say 16th) to avoid confusion.

Another way is to have a function that converts selected notes to tuplets (just like how reduced rest notes functions). You select notes you want to convert to tuplets, you use the "convert to tuplets" function, and it will find all selected notes by group of 3's, calculate the total duration to nearest 2^nth notes, then divide by 3 to set the new note length.

for example, if you select d+16&d+64e16.f16&f64, there are three notes in total: d+, e and f
the total duration is 30+36+30 = 96 ticks

Therefore, each note's duration should be 96/3 = 32 ticks, which means they should be 12th notes.
So after the conversion, they should be L12d+ef

**Comment by Lisedrika** [comment]
> I can understand the frustration but I know exactly why it happens.
> 
> The real issue is that, when converting from MIDI to MML, some midis (or tracks) are not perfectly quantized. Since a 64th note is only 6ticks (under 96TPQN condition), while a 48th note is 8 ticks. Some tracks can have an offset of 2~3 ticks (especially for instruments with longer attacks, like string instruments), if tuplets are allowed, we need to find a way to solve this issue.
> 
> Currently, what I am doing with midi files with large amount of tuplets, is to scale note length by 1.5 or 0.75 to get rid of 1/3 factors in note length, and make adjustments accordingly.
> 
> As for MabiIcco, I can think of two ways to improve (that will require a lot of hard works from Fourthline of course).
> 
> First way is to have a separate option to convert tuplets while importing midi. However, prior to converting, midi files needs to be quantized correctly, and starting time for each track need to be aligned to proper resolution (say 16th) to avoid confusion.
> 
> Another way is to have a function that converts selected notes to tuplets (just like how reduced rest notes functions). You select notes you want to convert to tuplets, you use the "convert to tuplets" function, and it will find all selected notes by group of 3's, calculate the total duration to nearest 2^nth notes, then divide by 3 to set the new note length.
> 
> for example, if you select d+16&d+64e16.f16&f64, there are three notes in total: d+, e and f the total duration is 30+36+30 = 96 ticks
> 
> Therefore, each note's duration should be 96/3 = 32 ticks, which means they should be 12th notes. So after the conversion, they should be L12d+ef


I think it's a good idea. However, this problem is not unique to Mabiico, and I remember that commercial programs are not completely solved. It's a technology that's easy to say, but difficult to implement.

**Comment by fourthline** [comment]
Thank you for your wonderful suggestion.
I made a test version. [v1.2.79](https://fourthline.jp/mabiicco/MabiIcco-1.2.79.zip)

1. Option to unalign when reading from MIDI: default is unaligned, options 2tick, 6tick can be selected
![image](https://user-images.githubusercontent.com/1832571/184480373-bdfacc9d-e803-4266-82f5-004cc77dc84f.png)

2. Convert to tuplet function: You can select multiple notes and execute from the right-click popup menu
![image](https://user-images.githubusercontent.com/1832571/184480327-b20e09ab-a37f-4094-a634-d0166088c1ec.png)

**Comment by Lisedrika** [comment]
> Thank you for your wonderful suggestion. I made a test version. [v1.2.79](https://fourthline.jp/mabiicco/MabiIcco-1.2.79.zip)
> 
> 1. Option to unalign when reading from MIDI: default is unaligned, options 2tick, 6tick can be selected
>    ![image](https://user-images.githubusercontent.com/1832571/184480373-bdfacc9d-e803-4266-82f5-004cc77dc84f.png)
> 2. Convert to tuplet function: You can select multiple notes and execute from the right-click popup menu
>    ![image](https://user-images.githubusercontent.com/1832571/184480327-b20e09ab-a37f-4094-a634-d0166088c1ec.png)

That's very cool! 
It is inconvenient to enter the end of the last note well, but it is encouraging that input that has not been possible.
And finally, Mabiicco can replace 3MLE completely.

There is one issue with optimization. 
Quintuplet (5) can be entered as L10. For the same reason, it is necessary to update the optimization algorithm by additionally registering as L5. (If you put in an option that you can enter with a mouse, I would be very happy.)
I think it can all be applied to the divisor of 960. Please check. 
- 1,2,3,4,5,6,8,10,12,15,16,20,24,30,32,40,48,60,64,80,96,120,160,192,240,320,480,960

**Comment by Lisedrika** [comment]
> I think it can all be applied to the divisor of 960. Please check.

And here is a test MML

https://drive.google.com/file/d/1qukk6uTWKUOWSXeQsIvNXaEkN97Ki-z7/view?usp=sharing

**Comment by fourthline** [comment]
Do you mean that you want to do something like the following?
`MML@r1l10<cccccccccc<gggggggggg>cccccccccc<ggggggggggr1>l9ccccccccc<ggggggggg>ccccccccc<gggggggggr1>l5ccccc<ggggg>ccccc<ggggg,l1rgegergegergege,;`

In the Mabinogi environment (96TPQN), L5 and L10 are not divisible, so I think they will be out of line with other notes.
![image](https://user-images.githubusercontent.com/1832571/184586121-ec99c9bc-2d7b-4f95-8c7d-d180e62fc6c7.png)

L1c = 384tick (96TPQN)
L10c = 38.4tick (Cannot be expressed under 96TPQN)

**Comment by Lisedrika** [comment]
> Do you mean that you want to do something like the following? `MML@r1l10<cccccccccc<gggggggggg>cccccccccc<ggggggggggr1>l9ccccccccc<ggggggggg>ccccccccc<gggggggggr1>l5ccccc<ggggg>ccccc<ggggg,l1rgegergegergege,;`
> 
> In the Mabinogi environment (96TPQN), L5 and L10 are not divisible, so I think they will be out of line with other notes. ![image](https://user-images.githubusercontent.com/1832571/184586121-ec99c9bc-2d7b-4f95-8c7d-d180e62fc6c7.png)
> 
> L1c = 384tick (96TPQN) L10c = 38.4tick (Cannot be expressed under 96TPQN)

Oh, I was confused for a moment. The present is the most accurate. 
Please forget the optimization feedback written above. :D

**Comment by Lisedrika** [comment]
Translation correction is required.

연표로 변환 ▶ 잇단음표로 변환

**Comment by fourthline** [comment]
Released in v1.2.80
