### ISSUE TITLE
Optimiation is not optimal

### ISSUE THREAD

**Issue by kernighan** [fourthline/mmlTools#79]
Imported a MIDI, the resulting track has:

'r1r2r8.'

Optimization should have at least reduced this to:

'r1.r8.'

**Comment by kernighan** [comment]
I suspect that the optimizer is treating rests the same way as notes.  I.e., it treats "r1r2" the same as "c1c2" but they should be handled differently since rests can be combined in an optimal fashion.

**Comment by fourthline** [comment]
https://github.com/fourthline/mmlTools/commit/446df44b3d089d30a80326622f44d1ef89db913d
Before:
- c1&c2&c8.
- r1r2r8.

After:
 - c1.&c8.
 - r1.r8.

etc...

**Comment by fourthline** [comment]
Released in v1.2.80
