### ISSUE TITLE
Ctrl+右クリック&ドラッグ選択機能の追加

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#80]
Mabiiccoのマウス右クリック&ドラッグ選択機能はとても便利です。
ここにその便利さを加える機能を一つ提案したいと思います。

現在は範囲選択を一度試みた後は、Ctrlを押しても音符を一つずつクリックして追加する必要があります。
Ctrlを押したまま範囲選択を何度も繰り返しできるように改善していただければ、
より多くの作業を一括で素早く処理することができます。

いつも改善に努めていただき、ありがとうございます。o(〃’▽’〃)o

**Comment by fourthline** [comment]
機能の提案ありがとうございます。
次バージョンで反映できると思います。

**Comment by fourthline** [comment]
[v1.2.81](http://fourthline.jp/mabiicco/MabiIcco-1.2.81.zip) で反映してみました。

**Comment by Lisedrika** [comment]
返事が遅くなりました。 機能は完璧に作動します。 今度新しい楽譜を作る時とても有用に使いました。 この場を借りて感謝の言葉を申し上げます。
