### ISSUE TITLE
特定の状況で「MML出力」機能を使用するとテンポがずれるバグが発生

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#81]
こんにちは。新しいバグが見つかり、情報提供いたします。 条件は次のとおりです。

- 3パートに何の音符もない状態でテンポを2回変更したとき
- 最初の条件を満たした状態でテンポコマンドが挿入されたパートがテンポコマンドの後ろに何の音符もない場合
- この楽譜をクリップボードに出力する場合、該当部分のテンポが変な位置に移動します。 (普通は後ろに移動するようです)

該当バグは文字数が足りず、他のパートで文字数を配分した楽譜をゲーム内でテスト中に発見されました。 v0を挿入するアルゴリズムと最適化アルゴリズムが互いに絡み合って起きたものと見られます。 テンポをちょうどバグが発生するその位置だけに入れるという状況は、普段は見づらいですね。

[tempo bug test.zip](https://github.com/fourthline/mmlTools/files/9542976/tempo.bug.test.zip)

したがって、バグを再現するためのmmiファイルを添付します。 簡単に確認するには、mabiicco2つを起動し、片方にmmiファイルを出力->もう片方にクリップボードで貼り付けると分かります。もちろん、この楽譜をクリップボードで出力してゲーム内で演奏してもそのまま再現されます。

**Comment by fourthline** [comment]
情報提供ありがとうございます。
問題の内容確認しましたので、修正したいと思います。

**Comment by fourthline** [comment]
[v1.2.81](http://fourthline.jp/mabiicco/MabiIcco-1.2.81.zip) で修正してみました。

**Comment by Lisedrika** [comment]
テスト完了です。 異常ありません。
