### ISSUE TITLE
mmlの文字数変更への対応

### ISSUE THREAD

**Issue by jkzisyaj** [fourthline/mmlTools#82]
2022年9月14日のアップデートにおいて、音声を使用しない場合、mmlに使用できる文字数が以下のように増加しました。

メイン: 1600
和音1: 1200
和音2: 900

これに対応した出力、およびザブキエル用の分割に対応をお願いします。

**Comment by fourthline** [comment]
歌パート除外機能は対応済みです。
https://github.com/fourthline/mmlTools/commit/a12bf462f9a4367a5a9a5ab9b5e56aae131886d0

**Comment by Lisedrika** [comment]
> 
下段のコーラスを選択するメニューに該当オプションがあります。

**Comment by Lisedrika** [comment]
> 2022年9月14日のアップデートにおいて、音声を使用しない場合、mmlに使用できる文字数が以下のように増加しました。
> 
> メイン: 1600 和音1: 1200 和音2: 900
> 
> これに対応した出力、およびザブキエル用の分割に対応をお願いします。

下段のコーラスを選択するメニューに該当オプションがあります。
