### ISSUE TITLE
楽譜の途中で拍子表変更機能導入の件

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#83]
いつもお世話になっております。
新機能導入の件でご連絡致しました。

![sample](https://user-images.githubusercontent.com/9856673/193751963-5ffee920-7a7c-40d9-a3a1-e59c6b8be869.png)

それは楽譜の途中で拍子表の変更ができるようにすることです。
これは現代音楽でよく使われる「不完全な処置(incomplete measure)」も一緒に解決できるので一石二鳥です。

できればマーカー、テンポと同じ方式で入力処理できればと思います。
しかし、これはプログラマー的な観点から提案したものではないので、他の方式でも入力が便利ならOKです。

お忙しいところ恐縮ですが、よろしくお願いいたします。

from Lisedrika

**Comment by fourthline** [comment]
お試し版 [v1.2.83](http://fourthline.jp/mabiicco/MabiIcco-1.2.83.zip) 作成してみました。
マーカーやテンポと同じ方式で設定できます。
![image](https://user-images.githubusercontent.com/1832571/198868562-2bd7270d-3931-4665-956f-922cdd8ac684.png)
![image](https://user-images.githubusercontent.com/1832571/198868572-a2c8e05d-64b8-40e5-ac1c-acdc5b394847.png)

**Comment by Lisedrika** [comment]
> お試し版 [v1.2.83](http://fourthline.jp/mabiicco/MabiIcco-1.2.83.zip) 作成してみました。 マーカーやテンポと同じ方式で設定できます。 ![image](https://user-images.githubusercontent.com/1832571/198868562-2bd7270d-3931-4665-956f-922cdd8ac684.png) ![image](https://user-images.githubusercontent.com/1832571/198868572-a2c8e05d-64b8-40e5-ac1c-acdc5b394847.png)

確認いたします.

**Comment by Lisedrika** [comment]
完璧です。
もうこのツールから抜け出せませんね。
ヽ(○´∀`)ﾉ♪

**Comment by Lisedrika** [comment]
ここにももう一つです！ 韓国語のメニュー名は修正が必要だと思います。 順番に表記します。

박자표 삽입
박자표 편집
박자표 제거

**Comment by fourthline** [comment]
ありがとうございます。
[v1.2.84](http://fourthline.jp/mabiicco/MabiIcco-1.2.84.zip) 修正しました。

**Comment by Lisedrika** [comment]
> ありがとうございます。 [v1.2.84](http://fourthline.jp/mabiicco/MabiIcco-1.2.84.zip) 修正しました。

彼は...神様だ!!
