### ISSUE TITLE
音符入力長変更短縮キー導入に関する件

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#84]
いつもお世話になっております。

「音符の入力長をショートカットキーに変えられたらいいな」という建議事項がよく入ってきてお伝えします。

一般的に1つの小さな楽譜を作る時も、音符の入力長を数千回~数万回変更します。 そのため、これを単純に上下短縮キーさえ適用するだけで莫大な効率向上を遂げることができるでしょう。

それではご検討のほど、よろしくおねがいいたします。

from Lisedrika

**Comment by fourthline** [comment]
「編集」→「キーボード入力」では、下記のキー割当がありますが同じでよいでしょうか？

- 1: 全音符
- 2: 2分音符
- 3: 4分音符
- 4: 8分音符
- 5: 16分音符
- 6: 32分音符
- 7: 64分音符
- 8: 12分音符
- 9: 24分音符
- 0: 48分音符

![image](https://user-images.githubusercontent.com/1832571/194814525-baa65d8b-e4a4-4aca-8717-30df47861817.png)
![image](https://user-images.githubusercontent.com/1832571/194814792-56a87bd6-d378-4150-82a0-fd2d4e72305b.png)

**Comment by Lisedrika** [comment]
> 「編集」→「キーボード入力」では、下記のキー割当がありますが同じでよいでしょうか？
> 
> * 1: 全音符
> * 2: 2分音符
> * 3: 4分音符
> * 4: 8分音符
> * 5: 16分音符
> * 6: 32分音符
> * 7: 64分音符
> * 8: 12分音符
> * 9: 24分音符
> * 0: 48分音符
> 
> ![image](https://user-images.githubusercontent.com/1832571/194814525-baa65d8b-e4a4-4aca-8717-30df47861817.png) ![image](https://user-images.githubusercontent.com/1832571/194814792-56a87bd6-d378-4150-82a0-fd2d4e72305b.png)

素晴らしいアイデアだと思います。
単純な上下移動よりは、これをグローバルショートカットキーにそのまま適用した方がよさそうですね。
♫꒰･◡･๑꒱

**Comment by fourthline** [comment]
お試し版 [v1.2.83](http://fourthline.jp/mabiicco/MabiIcco-1.2.83.zip) 作成してみました。
下記のショートカットキーを追加しています。
![image](https://user-images.githubusercontent.com/1832571/198868649-c356a7a2-07c6-469c-b43b-290b3a94e992.png)

**Comment by Lisedrika** [comment]
> お試し版 [v1.2.83](http://fourthline.jp/mabiicco/MabiIcco-1.2.83.zip) 作成してみました。 下記のショートカットキーを追加しています。 ![image](https://user-images.githubusercontent.com/1832571/198868649-c356a7a2-07c6-469c-b43b-290b3a94e992.png)

確認いたします.

**Comment by Lisedrika** [comment]
> お試し版 [v1.2.83](http://fourthline.jp/mabiicco/MabiIcco-1.2.83.zip) 作成してみました。 下記のショートカットキーを追加しています。 ![image](https://user-images.githubusercontent.com/1832571/198868649-c356a7a2-07c6-469c-b43b-290b3a94e992.png)

この機能も完璧に動作します。
プログラマの知人からキーボード右側のナンバーパッドにもこの機能を同じように接続してほしいという提案がありました。
これも可能でしょうか？

**Comment by fourthline** [comment]
[v1.2.84](http://fourthline.jp/mabiicco/MabiIcco-1.2.84.zip)
キー割当にナンバーパッド追加しました。
![image](https://user-images.githubusercontent.com/1832571/199665250-a11f2c78-1ef1-4b0c-ba31-dc7c5c0cde88.png)

**Comment by Lisedrika** [comment]
> [v1.2.84](http://fourthline.jp/mabiicco/MabiIcco-1.2.84.zip) キー割当にナンバーパッド追加しました。 ![image](https://user-images.githubusercontent.com/1832571/199665250-a11f2c78-1ef1-4b0c-ba31-dc7c5c0cde88.png)

これ以上望むことはありません。
