### ISSUE TITLE
機能改善提案

### ISSUE THREAD

**Issue by Dovidic** [fourthline/mmlTools#85]
様々なユーザーが要請した内容を集めてまとめてみました。

1. 高解像度で作業外領域クリック時にノートが入力されるバグを修正
- FHD超過時に下部領域が空になり、その領域をクリックするとo0c-位置にノートが入力されます。下段の映像と絵を参考にしてください。

![FHD 이상 화면 적용 문제](https://user-images.githubusercontent.com/88671533/199502841-44a0de38-93ca-4b8b-a15e-ecef90df667f.png)
図 1: それぞれ 3840X2160、2560X1440、1920X1080 解像度でノートサイズを 8px で適用した場合のスクリーンショットです。

https://user-images.githubusercontent.com/88671533/199502871-f10a3c13-489a-4004-b8af-d9b1614ad114.mp4
映像1(Link)：実際の適用映像です。

2. 音符の長さを変更するショートカット Num パッドのサポート要求
https://github.com/fourthline/mmlTools/issues/84
- 以前の課題で要請した事項ですが、再リクエストします。

3. ノート長のショートカットと複数の機能のカスタムキーマッピング機能のサポートをリクエスト
- ユーザーごとにおなじみのショートカットの組み合わせが異なることができるという点で要請した事項です。

4. MML出力時のトラックナンバーカラムの提供（トラック順序及び個数確認用）
- MML出力メニューを開くとトラック名/楽器/ランクが表示されますが、そのトラックが何番目のトラックかはわかりません。一番左にトラックナンバーを入れるとトラックの順番や個数確認が容易になると期待しています。下の図を参考にしてください。

![악기 출력 창에 번호가 달려있었으면 (단순 인원 확인용이므로 보이기만 해도 OK)_2](https://user-images.githubusercontent.com/88671533/199502043-63486aa3-c1b1-4646-bd57-620d5bbdf3c9.png)
図2：トラック名/楽器/ランクが表示されますが、トラック番号は表示されません。
![악기 출력 창에 번호가 달려있었으면 (단순 인원 확인용이므로 보이기만 해도 OK)](https://user-images.githubusercontent.com/88671533/199502076-0be6f3b1-a4b3-46ab-969c-d2f4ce059d3d.png)
図3：対応するウィンドウの左側に上記のようにトラック番号を挿入できます。

5. TXT形式でソング情報と楽器、MML出力機能を提供
- すでにmmiファイル自体を開くと、該当する情報を一部確認できますが、MMLが最適化された状態ではなく、情報を確認することも難しい問題があります。その機能をサポートしている場合は、TXTの形式でMMLを展開するのに非常に役立ちます。
ソング情報はファイル - 情報から呼び出され、各トラック情報に基づいてトラックの順序と楽器名を書き、曲パートを除外するか、トラックが1ランクを超える場合はMusic Bookを使用するかどうかをメモします。その後、各下部にMMLを出力します。

上記を考慮すると、テキストで出力するときは次のようになります（16人の合奏用楽譜を例示します）。

曲名：AAA
著者：BBB

1/16）リュート_ソングパートを除くY

MML@aaa,bbb,ccc,,;

2/16）ピアノ_ソングパートを除くN_Music Book（N）を使う

(1/N)
MML@ddd,eee,fff,;
(2/N)
MML@ggg,hhh,iii,;
...
(N/N)
MML@xxx,yyy,zzz,;

3/16)ピアノ_ソングパートを除くY

MML@jjj,kkk,lll,;

...

16/16)ヴァイオリン_ソングパートを除くY

MML@mmm,nnn,ooo,;

**Comment by fourthline** [comment]
>     1. 高解像度で作業外領域クリック時にノートが入力されるバグを修正
修正済みです。

>     2. 音符の長さを変更するショートカット Num パッドのサポート要求
対応済みです。 #84

>     3. ノート長のショートカットと複数の機能のカスタムキーマッピング機能のサポートをリクエスト
カスタムキーマッピング機能は予定ありません。

>     4. MML出力時のトラックナンバーカラムの提供（トラック順序及び個数確認用）
対応済みです。[v1.4.1](https://github.com/fourthline/mmlTools/releases/tag/v1.4.1)

>     5. TXT形式でソング情報と楽器、MML出力機能を提供
export機能という認識ですが、用途がよくわからず対応の予定ありません。

必要であれば、個別にIssue作成おねがいします。
