### ISSUE TITLE
トラックの色に関連するバグがあります。

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#86]
いつもお世話になっております。

編集するトラックをクリックして、変更するたびに別のトラックに割り当てられた色が変更される問題があります。
知人の情報提供によると、最近のバージョンで新たに発生したようです。

サンプル楽譜の9番目の節から1番トラック(ドラム)と3番トラック(ピアノ)を交互に選択してみてください。 2番トラック(ドラム)が緑と赤に交互に色が変わることが確認できます。

それではご検討のほど、よろしくおねがいいたします。

from Lisedrika

https://drive.google.com/file/d/1X1C--d1tNRMGDDZ1ww6G1-uYJoYBLwWL/view?usp=share_link

**Comment by fourthline** [comment]
すみません、下記によるバグのようです。
https://github.com/fourthline/mmlTools/commit/15223663a1257dcdad99997a21a2a6a7e869f5ab#diff-d4cfdaaa4745f0d685f7cfceeb083a99903c1e3bf1e1ee0929bd7ab8a6061043L614

修正しました。
[v1.2.85](http://fourthline.jp/mabiicco/MabiIcco-1.2.85.zip)

**Comment by Lisedrika** [comment]
> すみません、下記によるバグのようです。 [1522366#diff-d4cfdaaa4745f0d685f7cfceeb083a99903c1e3bf1e1ee0929bd7ab8a6061043L614](https://github.com/fourthline/mmlTools/commit/15223663a1257dcdad99997a21a2a6a7e869f5ab#diff-d4cfdaaa4745f0d685f7cfceeb083a99903c1e3bf1e1ee0929bd7ab8a6061043L614)
> 
> 修正しました。 [v1.2.85](http://fourthline.jp/mabiicco/MabiIcco-1.2.85.zip)

ありがとうございます。
