### ISSUE TITLE
「ボリューム調節」ショートカットキー追加提案

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#88]
こんにちは。毎度お疲れ様です。

前回追加していただいた音符の長さの短縮キーは非常に革新的でした。 とてもよく使っています。
今回はそれに劣らず、よく使う機能に対するショートカットキーをお願いしたいと思います。

それは選択した音符のボリュームを1ずつ上げたり下げたりするショートカットキーです。
Mabiiccoを使用しながら、いつも残念な点がボリューム調節をする時、手続きが複雑だということでした。
「音符を選んでから、簡単なショートカットでボリュームを調整できればいいな」と思いました。
ショートカットキーはAlt+Up(Down)が空いていますので、こちらに適用してはいかがでしょうか。

ご検討の程よろしくお願いします。(*´▽｀)/

from Lisedrika

**Comment by fourthline** [comment]
ご提案ありがとうございます。
ショートカットキーのほうがよいでしょうか？
たとえば、altキー+マウスwheel という案もあります。

**Comment by Lisedrika** [comment]
> 

Alt+マウスwheelまでは考えられませんでした。 それもいい方法だと思います。 
ところで、Ctrl+マウスwheelとShift+マウスwheelが
画面拡大、スクロールに関連した機能なので混同の余地があるのではないでしょうか？

例えば、Shift+Up(Down)が音程オクターブ移動（現在ある機能）、
Ctrl+Up(Down)が音程1マス(半音)移動、
Alt+Up(Down)がボリューム調節なら
統一性があっていいと思います。

**Comment by Lisedrika** [comment]
> ご提案ありがとうございます。 ショートカットキーのほうがよいでしょうか？ たとえば、altキー+マウスwheel という案もあります。

Alt+マウスwheelまでは考えられませんでした。 それもいい方法だと思います。
ところで、Ctrl+マウスwheelとShift+マウスwheelが
画面拡大、スクロールに関連した機能なので混同の余地があるのではないでしょうか？

例えば、Shift+Up(Down)が音程オクターブ移動（現在ある機能）、
Ctrl+Up(Down)が音程1マス(半音)移動、
Alt+Up(Down)がボリューム調節なら
統一性があっていいと思います。

**Comment by fourthline** [comment]
altショートカットはやや不都合がありました。
キーショートカットの場合は事前にノート選択が必要で、さらにマウスから手を離すかもしれません。
ピアノロール入力が基本なので、マウスから手を離さずに音量調節もできるといいなと思いました。
下記で考えてみました。
・ctrl+shift+up(down)：選択中ノートの音量上げ下げ
・ctrl+shift+wheel：マウスカーソル上ノートの音量上げ下げ、選択中ノートがある場合は選択中ノートの音量上げ下げ

**Comment by Lisedrika** [comment]
> altショートカットはやや不都合がありました。 キーショートカットの場合は事前にノート選択が必要で、さらにマウスから手を離すかもしれません。 ピアノロール入力が基本なので、マウスから手を離さずに音量調節もできるといいなと思いました。 下記で考えてみました。 ・ctrl+shift+up(down)：選択中ノートの音量上げ下げ ・ctrl+shift+wheel：マウスカーソル上ノートの音量上げ下げ、選択中ノートがある場合は選択中ノートの音量上げ下げ

そうですか。
私も実際に使ってみないと体感できると思います。
ショートカットキーの構成はfourthlineさんの意見に従います。(*￣▽￣)b

**Comment by fourthline** [comment]
色々試してみて、最初のご提案のAltで作ってみました。
・alt+up(down)：選択中ノートの音量上げ下げ
・alt+wheel：マウスカーソル上ノートの音量上げ下げ、選択中ノートがある場合は選択中ノートの音量上げ下げ

[v1.2.87](http://fourthline.jp/mabiicco/MabiIcco-1.2.87.zip)

**Comment by Lisedrika** [comment]
> 色々試してみて、最初のご提案のAltで作ってみました。 ・alt+up(down)：選択中ノートの音量上げ下げ ・alt+wheel：マウスカーソル上ノートの音量上げ下げ、選択中ノートがある場合は選択中ノートの音量上げ下げ
> 
> [v1.2.87](https://fourthline.jp/mabiicco/MabiIcco-1.2.87.zip)

テスト完了しました。 特に異常は見つかりませんでした。

**Comment by fourthline** [comment]
確認ありがとうございます。クローズします。
