### ISSUE TITLE
韓国語の翻訳に関する小さな修正要請です。

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#89]
こんにちは。毎度お疲れ様です。

翻訳時に生じる若干のぎこちない部分、用語が統一されていない部分を修正したものです。
ですから、急ぎの修正事項ではありません。
ご都合の良い時に一緒にアップデートしてください。

[appResource_ko.properties.zip](https://github.com/fourthline/mmlTools/files/10707685/appResource_ko.properties.zip)

From Lisedrika

**Comment by fourthline** [comment]
ありがとうございます。
次回リリースに取り込みたいと思います。

**Comment by fourthline** [comment]
v1.2.90へ反映しました
