### ISSUE TITLE
[enhancement]横スクロール量を設定にて変更可能に

### ISSUE THREAD

**Issue by angiodianxin** [fourthline/mmlTools#90]
いつも開発ありがとうございます。便利に使わせていただいています。

スクロールが小節単位になりましたが、個人的には以前の動作の方が使い勝手がよく思っています。
設定にて切り替えられるようになりませんでしょうか？

**Comment by fourthline** [comment]
ありがとうございます。
画像のようにしてみたいと思います。以前の動作が "6px固定" になります。
![image](https://user-images.githubusercontent.com/1832571/230714945-4a1b8de2-a73d-4e8f-9618-7b9547758dce.png)

**Comment by fourthline** [comment]
[v1.2.94](https://github.com/fourthline/mmlTools/releases/tag/v1.2.94) でリリースしました。

**Comment by angiodianxin** [comment]
ありがとうございます。確認できました
