### ISSUE TITLE
어떻게 해야 Tracks를 merge할 수 있습니까?

### ISSUE THREAD

**Issue by levelhoon** [fourthline/mmlTools#92]
i need it..

cuz ".mid" file을 load 후 너무 많은 Tracks가 존재하는 경우에는 실제로 게임안에서 사용하기 곤란합니다.
합주가 아닌 독주용 악보를 누구나 쉽게 만들었으면 좋겠다고 생각하고 있습니다.

**Comment by fourthline** [comment]
どのような機能があれば、実現できるでしょうか？
具体的なアイデアがあれば検討できると思います。
24トラック→1トラックは単純には変換できないと思います。
