### ISSUE TITLE
Note overlap機能が正常に動作しません。

### ISSUE THREAD

**Issue by Dovidic** [fourthline/mmlTools#93]
MabiKRでは正常に演奏されていますが、MabiIcco v1.2.94でNote overlap機能をallに設定しても、ノートが重複して演奏されずに切れることがわかりました。

[MabiIcco_v1.2.94_overlap.zip](https://github.com/fourthline/mmlTools/files/11212215/MabiIcco_v1.2.94_overlap.zip)

MabiKRで演奏した映像です。

https://youtu.be/kJd0XDt-vFw

**Comment by fourthline** [comment]
MabiJP では正常です。音は切れます。（2023/04/15時点）
また、提供いただいたMMLデータは楽器がピアノになっていますが、音源情報もoverlap ONであるため、overlap all設定としても動作は同じになります。

おそらく、MabiKRの演奏システム変更への対応が別に必要と思います。

**Comment by Dovidic** [comment]
> MabiJP では正常です。音は切れます。（2023/04/15時点） また、提供いただいたMMLデータは楽器がピアノになっていますが、音源情報もoverlap ONであるため、overlap all設定としても動作は同じになります。
> 
> おそらく、MabiKRの演奏システム変更への対応が別に必要と思います。

上の動画のように、現在MabiKRの再生システムは3ML Editorと同様にすべてのパートで音符を重ねても全部重なった音がします。 MabiJPもまもなく適用されます。

**Comment by fourthline** [comment]
詳細分かりませんが、3mleと同じなのであれば各パートを独立チャンネルにする感じだと思います。

**Comment by fourthline** [comment]
MabiIccoのテストバージョンを作成してみました。[v1.3.95](https://fourthline.jp/mabiicco/MabiIcco-1.3.95.zip)
- Overlap Mode 削除
- 各パートを独立チャンネルで再生するよう変更

**Comment by Dovidic** [comment]
> MabiIccoのテストバージョンを作成してみました。[v1.3.95](https://fourthline.jp/mabiicco/MabiIcco-1.3.95.zip)
> 
> * Overlap Mode 削除
> * 各パートを独立チャンネルで再生するよう変更

正常に動作しています。 ありがとうございます！
