### ISSUE TITLE
拍子表と節編集の連動に関する件

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#94]
こんにちは。毎度お疲れ様です。

節や拍子を挿入、削除したとき、マーカーとテンポコマンドはそれに合わせてすべて移動されます。 
しかし、拍子表表記は移動しません。 それで楽譜が作業中によく壊れていますね。
拍子表表記も節の挿入、削除に合わせて移動するように修正していただけますか？

どうぞよろしくお願いします。(*ˊᗜˋ*)/ᵗᑋᵃᐢᵏ ᵞᵒᵘ*

from Lisedrika

**Comment by fourthline** [comment]
ありがとうございます。
拍子指定もマーカーやテンポと同じように移動するよう修正したいと思います。

**Comment by fourthline** [comment]
すみません。
拍子指定は小節単位にする必要があるため、テンポやマーカーのように連動で移動できませんでした。

**Comment by Lisedrika** [comment]
> すみません。 拍子指定は小節単位にする必要があるため、テンポやマーカーのように連動で移動できませんでした。

そうでしたか。悲しいことですね。

**Comment by fourthline** [comment]
次のようにならできそうですが、問題ないでしょうか？混乱がないか心配しています。
・小節の挿入/削除 → 拍子記号も移動するようにする
・拍の挿入/削除 → 拍子記号は移動しない


なお、v1.3.97から小節の削除/拍の削除で拍子記号が削除されてしまいますが、これはバグなので修正する予定です。

**Comment by Lisedrika** [comment]
> 次のようにならできそうですが、問題ないでしょうか？混乱がないか心配しています。 ・小節の挿入/削除 → 拍子記号も移動するようにする ・拍の挿入/削除 → 拍子記号は移動しない
> 
> なお、v1.3.97から小節の削除/拍の削除で拍子記号が削除されてしまいますが、これはバグなので修正する予定です。


あ、そうですね.

拍子だけ削除する概念は 普通DAWにはないと思うし··· これは編集スタイルを完全に直してしまわない限り難しいですね。私も予想できなかった部分です。

解決するアイデアはありますが、現在はそうするのが一番いいですね。(*￣▽￣)d



※ 節の中間の拍子を削除した場合、手前の節は別に拍子を計算して追加の拍子表を自動的に付けてくれるとかいうアイデアがあります。 でも、これは開発者にとっても、ユーザーにとっても複雑すぎると感じる可能性があります。 いっそユーザーが仕様として受け入れたほうがいいんじゃないか··· と思います。

**Comment by fourthline** [comment]
[v1.4.0](https://github.com/fourthline/mmlTools/releases/tag/v1.4.0) で反映しました。
