### ISSUE TITLE
繰り返し再生機能が不完全です。

### ISSUE THREAD

**Issue by Dovidic** [fourthline/mmlTools#95]
最初の再生時点で繰り返し再生項目を有効にしてから再生すると、最後のノートまで再生後、最初の再生時点までに戻る機能は正常に動作しますが、データの多い楽譜から最後のノートまで再生した後、最初の再生時点までに戻っている間に遅延現象が 発生します。 どの基準でループが発生するかを知りたいです。

その動画は例です。 データが少ない場合、遅延現象がほとんど発生しないことを確認しました。

https://github.com/fourthline/mmlTools/assets/88671533/06c0c7a3-9625-415e-843e-88e52a6afee9

**Comment by fourthline** [comment]
> 最初の再生時点で繰り返し再生項目を有効にしてから再生すると、最後のノートまで再生後、最初の再生時点までに戻る機能は正常に動作しますが、データの多い楽譜から最後のノートまで再生した後、最初の再生時点までに戻っている間に遅延現象が 発生します。 どの基準でループが発生するかを知りたいです。

本issueの意図がわかりませんが、修正の予定はありません。
ループの基準はトラック終端です。
