### ISSUE TITLE
ビジュアル的なvelocity修正機能導入の件

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#96]
こんにちは。毎度お疲れ様です。

私はMabiIccoのビジュアル的な編集機能を非常にリスペクトしています。 
まさに革命的な環境改善だと評価したいと思います。
新しい方々がマビノギ作曲を楽しんでいらっしゃるのを見ると、私も大きなやりがいを感じます。
そこで、もう一度跳躍するための新機能を提案したいと思います。

音符のベロシティをマウスドラッグやクリックで
絵を描くように変更する機能が導入されてほしいです。

![vel](https://github.com/fourthline/mmlTools/assets/9856673/9a8dc438-1103-4edf-a484-a0a3789c3783)
多少大げさに話しましたが、DAWでよく見られる機能です。(画像はCubaseです)
仮想の線を1本描くだけで、数十本を超える音符のクレッシェンド表現などが可能です。
もちろん音符1つだけ選んで変更することも可能です。
このように効果の適用範囲設定は様々なオプションがありますが、
まずはユーザーが直接選択した音符にのみ適用するとしても、使用に大きく役立ちます。

![vel2](https://github.com/fourthline/mmlTools/assets/9856673/e8dae057-6dfc-4d9f-b202-a2be2e19970f)
位置はやっぱりここでしょうね。
(参照用の写真ですのでUIの色や大きさは無視しても構いません)
空間活用のために、この部分は折りたたんだり広げたりできればと思います。

ご検討くださいますようお願い申し上げます。

from Lisedrika

**Comment by fourthline** [comment]
ご提案ありがとうございます。
時間かかるかもしれませんが、検討してみます。

**Comment by fourthline** [comment]
画面上でマウスドラックにより直線をひき、それに沿って音量を編集するという形でよいでしょうか。

![image](https://github.com/fourthline/mmlTools/assets/1832571/7e1a77e0-2657-404e-a822-13b4beb13caf)

**Comment by Lisedrika** [comment]
> 画面上でマウスドラックにより直線をひき、それに沿って音量を編集するという形でよいでしょうか。
> 
> ![image](https://user-images.githubusercontent.com/1832571/273508872-7e1a77e0-2657-404e-a822-13b4beb13caf.png)

いいえ、それは適切ではないと思います。 
あくまで個別の音符をクリックで調節することを基本にした方がいいですね。

ただし、クリックを維持したまま線を描くようにマウスカーソルを移動すると、隣接した音符も適用される形式で行くと作業に便利です。

**Comment by Lisedrika** [comment]
> > 画面上でマウスドラックにより直線をひき、それに沿って音量を編集するという形でよいでしょうか。
> > ![image](https://user-images.githubusercontent.com/1832571/273508872-7e1a77e0-2657-404e-a822-13b4beb13caf.png)
> 
> いいえ、それは適切ではないと思います。 あくまで個別の音符をクリックで調節することを基本にした方がいいですね。
> 
> ただし、クリックを維持したまま線を描くようにマウスカーソルを移動すると、隣接した音符も適用される形式で行くと作業に便利です。

これ、映像で説明した方がいいですね。 添付いたします。

https://github.com/fourthline/mmlTools/assets/9856673/57e16e04-7fa3-4cce-bbea-76d0b4607e2e

**Comment by Lisedrika** [comment]
> > > 画面上でマウスドラックにより直線をひき、それに沿って音量を編集するという形でよいでしょうか。
> 
> > > ![image](https://user-images.githubusercontent.com/1832571/273508872-7e1a77e0-2657-404e-a822-13b4beb13caf.png)
> 
> > 
> 
> > いいえ、それは適切ではないと思います。 あくまで個別の音符をクリックで調節することを基本にした方がいいですね。
> 
> > 
> 
> > ただし、クリックを維持したまま線を描くようにマウスカーソルを移動すると、隣接した音符も適用される形式で行くと作業に便利です。
> 
> 
> 
> これ、映像で説明した方がいいですね。 添付いたします。
> 
> 
> 
> https://github.com/fourthline/mmlTools/assets/9856673/57e16e04-7fa3-4cce-bbea-76d0b4607e2e
> 
> 
> 
> 
> 
> 機能の基調はこのようにして、MabiIccoではユーザーが選択した音符にのみマウスクリックまたはクリックしてドラッグを適用させれば完璧だと思われます。
> 
> 
> 
> このように製作する場合、ある面ではCubaseより良い点がありますね

映像で現れるこれらの機能は具現しなくてもよさそうです 

- valocity数値によってノートの色が変わる機能 
- valocity変更時に音が出る機能

**Comment by fourthline** [comment]
映像での解説ありがとうございます。
鉛筆ツールでの作業ですね。
私はcubaseは使ったことないのでマニュアルで確認してみましたが、マウスドラッグで直線を引いて入力するラインツールもあるようですね。
私が参考にしているdominoでもラインツールがあり、鉛筆ツールに似たフリーラインの入力も可能になっています。他にも様々なツールがありますが、MabiIccoではまずは鉛筆ツールとラインツールを作ってみたいと思います。

**Comment by fourthline** [comment]
鉛筆ツールの画像です。マウス押下後のドラッグで、ドラッグした軌跡に沿ってVelocity変更します。
![image](https://github.com/fourthline/mmlTools/assets/1832571/47bc4bb7-3b11-46fc-aa96-1d2bd34bb3c7)

**Comment by Lisedrika** [comment]
> 鉛筆ツールの画像です。マウス押下後のドラッグで、ドラッグした軌跡に沿ってVelocity変更します。 ![image](https://user-images.githubusercontent.com/1832571/276040772-47bc4bb7-3b11-46fc-aa96-1d2bd34bb3c7.png)

想像しただけでもすごいです。 早く使ってみたいです。(｡￫∀￩｡)

**Comment by fourthline** [comment]
テストバージョンを作成してみました。
[v1.4.1+VE](https://fourthline.jp/mabiicco/MabiIcco-1.4.1-VE.zip)

「設定」＞「音量エディタ」で有効になります。
Pアイコンが鉛筆モード、Lアイコンがラインモードになります。

![image](https://github.com/fourthline/mmlTools/assets/1832571/f9cb8809-834e-4ddb-bad8-1b88369b391f)

**Comment by Lisedrika** [comment]
> テストバージョンを作成してみました。 [v1.4.1+VE](https://fourthline.jp/mabiicco/MabiIcco-1.4.1-VE.zip)
> 
> 「設定」＞「音量エディタ」で有効になります。 Pアイコンが鉛筆モード、Lアイコンがラインモードになります。
> 
> ![image](https://user-images.githubusercontent.com/1832571/277580447-f9cb8809-834e-4ddb-bad8-1b88369b391f.png)

今使ってみましたが、うまく動作します。 
カスタムトリプレットでも問題ないですね。

思ったよりはるかによく開発されたようです。
本当にありがとうございます。

他のユーザーの方々のテスト結果も一緒に聞いてみるといいと思います。

**Comment by Lisedrika** [comment]
> テストバージョンを作成してみました。
> 
> [v1.4.1+VE](https://fourthline.jp/mabiicco/MabiIcco-1.4.1-VE.zip)
> 
> 
> 
> 「設定」＞「音量エディタ」で有効になります。
> 
> Pアイコンが鉛筆モード、Lアイコンがラインモードになります。
> 
> 
> 
> ![image](https://github.com/fourthline/mmlTools/assets/1832571/f9cb8809-834e-4ddb-bad8-1b88369b391f)
> 
> 

![image](https://github.com/fourthline/mmlTools/assets/9856673/cdbecce1-d18a-4287-a202-0f00be83454d)

他の方からフィードバックが入ってきました。 低い倍率の画面でも視認性がよくなるようにしてほしいという要請です。 

私の個人的な考えでは30~50%程度幅を縮小したらどうかと思います。

**Comment by fourthline** [comment]
フィードバックありがとうございます。
幅は小さすぎると操作性が悪くなるかもしれないので、
設定値で変えられるようにしてみたいと思います。
![image](https://github.com/fourthline/mmlTools/assets/1832571/88dde07f-94b9-47c0-a9a3-314b973cf23a)

**Comment by fourthline** [comment]
テストバージョン修正版です。
音量棒の幅を設定できるようにしました。また表示の細部を修正しています。

[v1.4.1+VE2](https://fourthline.jp/mabiicco/MabiIcco-1.4.1-VE2.zip)

翻訳のほうは問題ないでしょうか？
`velocity_editor=音量エディタ`
`velocity_editor.width=音量棒の幅`
`velocity_editor.mode.pencil=鉛筆モード`
`velocity_editor.mode.line=ラインモード`

`velocity_editor=볼륨 편집기`
`velocity_editor.width=볼륨 바 너비`
`velocity_editor.mode.pencil=연필 모드`
`velocity_editor.mode.line=라인 모드`

**Comment by fourthline** [comment]
ご確認ありがとうございます。

**Comment by fourthline** [comment]
[v1.4.2](https://github.com/fourthline/mmlTools/releases/tag/v1.4.2) でリリースしました。

**Comment by Lisedrika** [comment]
> [v1.4.2](https://github.com/fourthline/mmlTools/releases/tag/v1.4.2) でリリースしました。

お疲れ様でした。♡ ٩(´▽`)۶ ♡
