### ISSUE TITLE
ザブキエル楽譜集出力機能の誤り

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#97]
こんにちは。毎度お疲れ様です。

ザブキエル楽譜集出力機能の画面に対するエラー情報が入ってきてお伝えします。

![image](https://github.com/fourthline/mmlTools/assets/9856673/0065a05f-a224-443c-a0a8-fe3dcee9c2b1)

以前のバージョンは正常に動作し、1.4.0バージョンから新しくできたバグだそうです。 
私のパソコンでも同じ現象が発生することを確認しました。

ご検討くださいますようお願い申し上げます。

from Lisedrika

**Comment by fourthline** [comment]
ご連絡ありがとうございます。
修正したいと思います。

**Comment by fourthline** [comment]
[v1.4.1](https://github.com/fourthline/mmlTools/releases/tag/v1.4.1) で修正しました。
