### ISSUE TITLE
ザブキエル用として分割された楽譜を統合する機能に関する件

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#98]
いつもお世話になっています。

今もtxtファイルの形で楽譜を共有する方がたくさんいらっしゃいます。
今日は彼についてお願いしたく、ご連絡いたしました。

一般的な楽譜なら全く問題ありませんが、
ザブキエル用の楽譜をTXTファイルで共有してもらった場合、
MabiIccoからいちいち読み込んで手作業で貼らなければなりません。
（この時点で多くの方々がパニックに陥ります）

ですから、何か方法が必要だと思います。
私が考えたアイデアはこうです。

1) MML出力機能のインターフェースを活用して「トラックマージ（merge）」機能を開発。
2) ユーザーは別途のウィンドウでザブキエル用に分割された楽譜を1つずつ貼り付ける。（楽譜の内容まで別に見えなくても、貼り付けが正常になったという表示はしてほしいです）
3) 確認ボタンを押すと、一番後ろに併合が完了したトラックが新規作成される。

ご検討のほど、よろしくお願いいたします。

from Lisedrika

**Comment by fourthline** [comment]
ありがとうございます。
txtファイルに分割済みのサブキエル用のMMLがあり、それを取り込みたいということでよいでしょうか。

下記のようなイメージでよいでしょうか。「x import」（仮称）で分割されたMMLを貼り付けしていき、統合して読み込みます。
![image](https://github.com/fourthline/mmlTools/assets/1832571/71fdeb7a-ce9f-4fe1-a490-29426a76606d)

**Comment by Lisedrika** [comment]
> ありがとうございます。 txtファイルに分割済みのサブキエル用のMMLがあり、それを取り込みたいということでよいでしょうか。
> 
> 下記のようなイメージでよいでしょうか。「x import」（仮称）で分割されたMMLを貼り付けしていき、統合して読み込みます。 ![image](https://private-user-images.githubusercontent.com/1832571/287947185-71fdeb7a-ce9f-4fe1-a490-29426a76606d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjUwNzIsIm5iZiI6MTcwMTc2NDc3MiwicGF0aCI6Ii8xODMyNTcxLzI4Nzk0NzE4NS03MWZkZWI3YS1jZTlmLTRmZTEtYTQ5MC0yOTQyNmE3NjYwNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDVUMDgyNjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDdlMzJmYzc2ZjI2NmZhMzRhODAxYzYyMGM1NWJkMmVmZTUzOTk5ZWE4ZGMyZDFkOTEyMjFjZGFhNmM0ZGRjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JvdibjkeCW3gl5bqW48aD27LJTYwck2CdTmoLh6sHjE)


いつも思っていたよりディテールに作業してくださってありがとうございます。

最初のウィンドウでユーザーがpasteとdoneの違いを区別するのは難しいと思います。 
このように2重にレイアウトを変更したらどうでしょうか？ 
deleteボタンは、入力された1つのパーツをもう一度空けるボタンです。

![image](https://github.com/fourthline/mmlTools/assets/9856673/d80cac28-9af7-4643-adee-fb63e114560e)

**Comment by fourthline** [comment]
ありがとうございます。

![image](https://github.com/fourthline/mmlTools/assets/1832571/358b1556-bf93-4b0c-a215-f43eeedfa1af)
統合後のRank表示と、歌パート除外のオプションを追加してみました。

翻訳まだですが、テストバージョンを作成してみました。
[1.4.2+XI](https://fourthline.jp/mabiicco/MabiIcco-1.4.2+XI.zip)

トラックメニューの "MML@楽譜集インポート" / "MML collection import" です。

**Comment by Lisedrika** [comment]
> ありがとうございます。
> 
> ![image](https://private-user-images.githubusercontent.com/1832571/289235743-358b1556-bf93-4b0c-a215-f43eeedfa1af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMTc4MzEsIm5iZiI6MTcwMjExNzUzMSwicGF0aCI6Ii8xODMyNTcxLzI4OTIzNTc0My0zNThiMTU1Ni1iZjkzLTRiMGMtYTIxNS1mNDNlZWVkZmExYWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMTAyNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzg2ZjNmYWQ0MGMxMDE2ZDAyOWY3YjRiNTZkNTlhZjc4NThkYjI3YjliNGIxMDEyYjk5ZTg5MmYyMmI0M2U1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.as2Mzv30rP5DgwFKQtIYRRa80Ctief-wOPKFDRAkMzo) 統合後のRank表示と、歌パート除外のオプションを追加してみました。
> 
> 翻訳まだですが、テストバージョンを作成してみました。 [1.4.2+XI](https://fourthline.jp/mabiicco/MabiIcco-1.4.2+XI.zip)
> 
> トラックメニューの "MML@楽譜集インポート" / "MML collection import" です。

まずは私の楽譜でテストを行いましたが、特に機能的な異常は見つかりませんでした。

**Comment by fourthline** [comment]
テストありがとうございます。
韓国語の翻訳は下記でよいでしょうか。

| ja | ko |
|--------|--------|
| MML楽譜集インポート | MML악보집 가져오기 |
| MML楽譜集エクスポート | MML악보집 내보내기 |
| 分割されたMML | 분할된 MML |
| 貼り付け | 붙여넣기 |
| 削除 | 삭제 | 
| 変換する | 변환하다 | 
| キャンセル | 취소 |

**Comment by Lisedrika** [comment]
> ja	ko
> MML楽譜集インポート	MML악보집 가져오기
> MML楽譜集エクスポート	MML악보집 내보내기
> 分割されたMML	분할된 MML
> 貼り付け	붙여넣기
> 削除	삭제
> 変換する	변환하다
> キャンセル	취소

<html>
<body>

ja | ko
-- | --
MML楽譜集インポート | 자브키엘의 악보집 가져오기
MML楽譜集エクスポート | 자브키엘의 악보집 내보내기
分割されたMML | 분할된 MML
貼り付け | 붙여넣기
削除 | 지우기
変換する | 합치기
キャンセル | 취소


</body>
</html>


これでお願いします。

**Comment by fourthline** [comment]
ありがとうございます。
とても助かります。

**Comment by fourthline** [comment]
[v1.4.3](https://github.com/fourthline/mmlTools/releases/tag/v1.4.3) でリリースしました。

**Comment by Lisedrika** [comment]
> [v1.4.3](https://github.com/fourthline/mmlTools/releases/tag/v1.4.3) でリリースしました。

本当にありがとうございます。
いつも尊敬しています。

**Comment by fourthline** [comment]
ご提案ありがとうございました。
