### ISSUE TITLE
画面拡大、縮小時に横スクロール位置が他の場所に飛ぶバグ

### ISSUE THREAD

**Issue by Lisedrika** [fourthline/mmlTools#99]
いつもお世話になっています。

バグの発動条件は非常に簡単です。
タイトルに書いた通り、作業中にCtrl+マウスホイールで画面を拡大、縮小すると、
ある瞬間横スクロールが突拍子もない位置に急に移動します。

再生バーの位置かな？ 思いましたが、それは違うと思います。 
そして、ほとんどの場合、前方方向に一定量瞬間移動するようです。

https://github.com/fourthline/mmlTools/assets/9856673/95ed9182-a432-4ee3-bc43-abdd960483de

かなり多くの方から寄せられた情報提供ですが、
私も最近めっきり不便を感じるようになりお伝えします。

ご検討のほど、よろしくお願いいたします。

from Lisedrika

**Comment by fourthline** [comment]
情報ありがとうございます。
50回ほど試してみましたが、私のPCでは現象は発生しておりません。
発生頻度は高いのでしょうか？

**Comment by Lisedrika** [comment]
> 情報ありがとうございます。 50回ほど試してみましたが、私のPCでは現象は発生しておりません。 発生頻度は高いのでしょうか？

おそらく特定の条件がもっとあるようですね。 私の記憶では後半部で多く発生したようです。

映像の楽譜は他の方のものなので、私のものを追加で添付します。 
72 節、65 節などで固定的に発生します。

[20240104_MEI.zip](https://github.com/fourthline/mmlTools/files/13848600/20240104_MEI.zip)

**Comment by fourthline** [comment]
追加情報ありがとうございます。
私のPCでも現象確認できました。

- JDK17 (既存): 発生
- JDK21: 発生
- revalidate追加: 発生
- invokeLater: ちらつくのでダメ
- ログをいれると発生頻度が落ちる

#### 回避策

- 既存対策コードを1回実行→2回実行で解消するよう。
- 遅延コードでもOKなよう。

次回リリースで修正したいと思います。

**Comment by fourthline** [comment]
[v1.5.0](https://github.com/fourthline/mmlTools/releases/tag/v1.5.0) のリリースで修正反映しました。
